-- Lote 1: desayunos y cenas rápidas (80 recetas)

-- ===========================
-- DESAYUNOS (25)
-- ===========================

-- D01
select seed_recipe($json$ {"nombre": "Tostadas con tomate, ajo y aceite", "descripcion": "El desayuno andaluz de toda la vida con pan tostado y tomate rallado.", "instrucciones": "Tuesta el pan\nRalla el tomate y frota el ajo sobre el pan\nReparte el tomate sobre las tostadas\nAliña con aceite de oliva y sal", "raciones": 2, "prep_min": 5, "cocina_min": 5, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "pan", "q": 4, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D02
select seed_recipe($json$ {"nombre": "Porridge de avena con plátano", "descripcion": "Gachas calientes de avena con plátano y un toque de canela.", "instrucciones": "Calienta la leche en un cazo\nAñade la avena y cuece 5 minutos removiendo\nCorta el plátano en rodajas\nSirve el porridge con el plátano, la miel y la canela por encima", "raciones": 2, "prep_min": 5, "cocina_min": 7, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "avena", "q": 100, "u": "g"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "plátano", "q": 1, "u": "pieza"}, {"n": "miel", "q": 1, "u": "cda"}, {"n": "canela", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D03
select seed_recipe($json$ {"nombre": "Yogur griego con fresas, miel y nueces", "descripcion": "Bol fresco de yogur griego con fruta de temporada y crujiente de nueces.", "instrucciones": "Lava y corta las fresas en cuartos\nReparte el yogur griego en dos boles\nAñade las fresas y las nueces troceadas\nRiega con la miel", "raciones": 2, "prep_min": 7, "cocina_min": 0, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "primavera", "batch_days": 1, "principal": "yogur", "ingredientes": [{"n": "yogur griego", "q": 2, "u": "pieza"}, {"n": "fresas", "q": 200, "u": "g"}, {"n": "nueces", "q": 30, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D04
select seed_recipe($json$ {"nombre": "Tortilla francesa con tostadas", "descripcion": "Tortilla francesa esponjosa acompañada de pan tostado con aceite.", "instrucciones": "Bate los huevos con una pizca de sal\nCuaja la tortilla en una sartén con un poco de aceite\nTuesta el pan y alíñalo con aceite\nSirve la tortilla con las tostadas", "raciones": 2, "prep_min": 5, "cocina_min": 8, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D05
select seed_recipe($json$ {"nombre": "Revuelto de champiñones al ajillo", "descripcion": "Huevos revueltos cremosos con champiñones salteados con ajo.", "instrucciones": "Lamina los champiñones y el ajo\nSaltéalos en una sartén con aceite hasta dorar\nAñade los huevos batidos con sal y remueve a fuego suave\nSirve sobre el pan tostado", "raciones": 2, "prep_min": 8, "cocina_min": 10, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "champiñones", "q": 200, "u": "g"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D06
select seed_recipe($json$ {"nombre": "Tosta de aguacate con huevo", "descripcion": "Tosta de pan con aguacate machacado, huevo a la plancha y limón.", "instrucciones": "Tuesta el pan\nMachaca el aguacate con limón y sal\nHaz los huevos a la plancha con un poco de aceite\nMonta las tostas con el aguacate y el huevo encima", "raciones": 2, "prep_min": 8, "cocina_min": 5, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "pan", "q": 2, "u": "pieza"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D07
select seed_recipe($json$ {"nombre": "Sándwich mixto de jamón y queso", "descripcion": "El clásico mixto a la plancha, dorado por fuera y fundente por dentro.", "instrucciones": "Monta los sándwiches con el jamón cocido y el queso\nUnta el exterior con mantequilla\nTuéstalos en la sartén por ambos lados hasta dorar\nCorta por la mitad y sirve caliente", "raciones": 2, "prep_min": 5, "cocina_min": 6, "tags": ["desayuno", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "pan de molde", "q": 4, "u": "pieza"}, {"n": "jamón cocido", "q": 80, "u": "g"}, {"n": "queso curado", "q": 60, "u": "g"}, {"n": "mantequilla", "q": 20, "u": "g"}]} $json$::jsonb);

-- D08
select seed_recipe($json$ {"nombre": "Bol de yogur con manzana y avena", "descripcion": "Bol de yogur natural con manzana troceada, avena y canela.", "instrucciones": "Trocea la manzana en dados pequeños\nReparte el yogur en dos boles\nAñade la manzana y la avena\nEspolvorea canela y riega con miel", "raciones": 2, "prep_min": 7, "cocina_min": 0, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "yogur", "ingredientes": [{"n": "yogur natural", "q": 2, "u": "pieza"}, {"n": "manzana", "q": 1, "u": "pieza"}, {"n": "avena", "q": 60, "u": "g"}, {"n": "canela", "q": 1, "u": "cdta"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D09
select seed_recipe($json$ {"nombre": "Tortitas de avena y plátano", "descripcion": "Tortitas saludables de tres ingredientes hechas a la sartén.", "instrucciones": "Tritura el plátano con los huevos y la avena\nDeja reposar la masa 5 minutos\nCuaja tortitas pequeñas en una sartén engrasada con mantequilla\nSirve con un hilo de miel", "raciones": 2, "prep_min": 8, "cocina_min": 12, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "avena", "q": 90, "u": "g"}, {"n": "plátano", "q": 1, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "mantequilla", "q": 15, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D10
select seed_recipe($json$ {"nombre": "Tosta de queso fresco, tomate y orégano", "descripcion": "Tosta ligera con queso fresco, rodajas de tomate y orégano.", "instrucciones": "Tuesta el pan\nCorta el tomate y el queso fresco en rodajas\nMonta las tostas alternando tomate y queso\nAliña con aceite, sal y orégano", "raciones": 2, "prep_min": 7, "cocina_min": 3, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pan", "q": 2, "u": "pieza"}, {"n": "queso fresco", "q": 150, "u": "g"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D11
select seed_recipe($json$ {"nombre": "Batido de fresas y plátano con avena", "descripcion": "Batido cremoso y saciante para empezar el día con energía.", "instrucciones": "Lava las fresas y pela el plátano\nPon la fruta, la leche, la avena y la miel en la batidora\nTritura hasta obtener una textura fina\nSirve bien frío", "raciones": 2, "prep_min": 8, "cocina_min": 0, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "primavera", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "fresas", "q": 200, "u": "g"}, {"n": "plátano", "q": 1, "u": "pieza"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "avena", "q": 40, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D12
select seed_recipe($json$ {"nombre": "Huevos revueltos con jamón serrano", "descripcion": "Revuelto cremoso con virutas de jamón serrano sobre pan tostado.", "instrucciones": "Trocea el jamón serrano\nBate los huevos y cuájalos a fuego suave con un poco de aceite\nAñade el jamón al final y mezcla\nSirve sobre el pan tostado", "raciones": 2, "prep_min": 5, "cocina_min": 8, "tags": ["desayuno", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "jamón serrano", "q": 60, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D13
select seed_recipe($json$ {"nombre": "Gachas de avena con manzana y nueces", "descripcion": "Avena cremosa cocida en leche con manzana salteada y nueces.", "instrucciones": "Cuece la avena en la leche durante 5 minutos\nTrocea la manzana en dados\nMezcla la manzana con las gachas\nSirve con nueces y canela por encima", "raciones": 2, "prep_min": 5, "cocina_min": 10, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "invierno", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "avena", "q": 100, "u": "g"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "manzana", "q": 1, "u": "pieza"}, {"n": "nueces", "q": 25, "u": "g"}, {"n": "canela", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D14
select seed_recipe($json$ {"nombre": "Tosta de requesón con miel y nueces", "descripcion": "Tosta dulce de requesón cremoso con miel y nueces troceadas.", "instrucciones": "Tuesta el pan\nUnta una capa generosa de requesón\nReparte las nueces troceadas\nRiega con miel y un toque de canela", "raciones": 2, "prep_min": 6, "cocina_min": 3, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pan", "q": 2, "u": "pieza"}, {"n": "requesón", "q": 150, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}, {"n": "nueces", "q": 30, "u": "g"}, {"n": "canela", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D15
select seed_recipe($json$ {"nombre": "Pan con tomate y jamón serrano", "descripcion": "Tostadas catalanas con tomate untado y lonchas de jamón serrano.", "instrucciones": "Tuesta el pan\nRalla el tomate y úntalo en las tostadas\nAliña con aceite de oliva y sal\nCorona con el jamón serrano", "raciones": 2, "prep_min": 6, "cocina_min": 4, "tags": ["desayuno", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "pan", "q": 4, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "jamón serrano", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D16
select seed_recipe($json$ {"nombre": "Bocadillo de tortilla francesa", "descripcion": "Bocadillo caliente de tortilla francesa recién hecha.", "instrucciones": "Bate los huevos con sal\nCuaja dos tortillas finas en la sartén con aceite\nAbre el pan y rellénalo con la tortilla\nSirve recién hecho", "raciones": 2, "prep_min": 5, "cocina_min": 8, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "pan", "q": 2, "u": "pieza"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D17
select seed_recipe($json$ {"nombre": "Yogur con naranja y almendras", "descripcion": "Bol de yogur con gajos de naranja, almendras y un hilo de miel.", "instrucciones": "Pela la naranja y sepárala en gajos\nReparte el yogur en dos boles\nAñade la naranja y las almendras troceadas\nRiega con la miel", "raciones": 2, "prep_min": 7, "cocina_min": 0, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "invierno", "batch_days": 1, "principal": "yogur", "ingredientes": [{"n": "yogur natural", "q": 2, "u": "pieza"}, {"n": "naranja", "q": 2, "u": "pieza"}, {"n": "almendras", "q": 30, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D18
select seed_recipe($json$ {"nombre": "Torrijas rápidas a la sartén", "descripcion": "Pan de molde empapado en leche con canela y dorado en mantequilla.", "instrucciones": "Mezcla la leche con la canela y la mitad del azúcar\nEmpapa el pan de molde y pásalo por huevo batido\nDóralo en la sartén con mantequilla por ambos lados\nEspolvorea con el resto del azúcar antes de servir", "raciones": 2, "prep_min": 8, "cocina_min": 10, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "pan de molde", "q": 4, "u": "pieza"}, {"n": "leche", "q": 200, "u": "ml"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "azúcar", "q": 30, "u": "g"}, {"n": "canela", "q": 1, "u": "cdta"}, {"n": "mantequilla", "q": 20, "u": "g"}]} $json$::jsonb);

-- D19
select seed_recipe($json$ {"nombre": "Avena nocturna con fresas", "descripcion": "Overnight oats con yogur y fresas, listo al levantarse.", "instrucciones": "Mezcla la avena con la leche y el yogur en dos tarros\nAñade la miel y remueve\nDeja reposar en la nevera toda la noche\nSirve por la mañana con las fresas troceadas", "raciones": 2, "prep_min": 10, "cocina_min": 0, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce", "fiambrera"], "temporada": "primavera", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "avena", "q": 100, "u": "g"}, {"n": "leche", "q": 250, "u": "ml"}, {"n": "yogur natural", "q": 1, "u": "pieza"}, {"n": "fresas", "q": 150, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D20
select seed_recipe($json$ {"nombre": "Tosta de aguacate y queso feta", "descripcion": "Tosta cremosa de aguacate con queso feta desmenuzado y limón.", "instrucciones": "Tuesta el pan\nMachaca el aguacate con zumo de limón y sal\nUnta las tostas y desmenuza el feta por encima\nTermina con un hilo de aceite de oliva", "raciones": 2, "prep_min": 8, "cocina_min": 3, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "pan", "q": 2, "u": "pieza"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 80, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D21
select seed_recipe($json$ {"nombre": "Revuelto de espinacas con queso", "descripcion": "Huevos revueltos con espinacas salteadas y queso rallado fundido.", "instrucciones": "Saltea las espinacas en una sartén con aceite\nAñade los huevos batidos con sal\nRemueve a fuego suave hasta que cuajen\nIncorpora el queso rallado y sirve con pan tostado", "raciones": 2, "prep_min": 6, "cocina_min": 9, "tags": ["desayuno", "rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "espinacas", "q": 150, "u": "g"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D22
select seed_recipe($json$ {"nombre": "Wrap dulce de plátano y chocolate", "descripcion": "Tortilla de trigo rellena de plátano y chocolate negro fundido.", "instrucciones": "Funde el chocolate negro al baño maría o al microondas\nUnta las tortillas con el chocolate\nAñade el plátano en rodajas y un hilo de miel\nEnrolla y dora 1 minuto por lado en la sartén", "raciones": 2, "prep_min": 8, "cocina_min": 5, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pan", "ingredientes": [{"n": "tortillas de trigo", "q": 2, "u": "pieza"}, {"n": "plátano", "q": 2, "u": "pieza"}, {"n": "chocolate negro", "q": 40, "u": "g"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- D23
select seed_recipe($json$ {"nombre": "Porridge de chocolate negro", "descripcion": "Avena cremosa con chocolate negro fundido y plátano.", "instrucciones": "Cuece la avena en la leche 5 minutos\nAparta del fuego y añade el chocolate troceado\nRemueve hasta que se funda\nSirve con el plátano en rodajas por encima", "raciones": 2, "prep_min": 5, "cocina_min": 8, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "invierno", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "avena", "q": 90, "u": "g"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "chocolate negro", "q": 30, "u": "g"}, {"n": "plátano", "q": 1, "u": "pieza"}]} $json$::jsonb);

-- D24
select seed_recipe($json$ {"nombre": "Huevos a la plancha con bacon", "descripcion": "Desayuno contundente de huevos a la plancha con bacon crujiente.", "instrucciones": "Dora el bacon en la sartén sin aceite hasta que quede crujiente\nHaz los huevos a la plancha con un poco de aceite\nSalpimienta los huevos\nSirve con el pan tostado", "raciones": 2, "prep_min": 4, "cocina_min": 10, "tags": ["desayuno", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "bacon", "q": 80, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- D25
select seed_recipe($json$ {"nombre": "Cuscús dulce con manzana y canela", "descripcion": "Cuscús hidratado en leche caliente con manzana, almendras y canela.", "instrucciones": "Calienta la leche con la canela\nVierte sobre el cuscús, tapa y deja reposar 5 minutos\nTrocea la manzana en dados\nMezcla todo y sirve con almendras y miel", "raciones": 2, "prep_min": 7, "cocina_min": 6, "tags": ["desayuno", "rapida", "sin-horno", "veggie", "dulce"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "avena", "ingredientes": [{"n": "cuscús", "q": 100, "u": "g"}, {"n": "leche", "q": 300, "u": "ml"}, {"n": "manzana", "q": 1, "u": "pieza"}, {"n": "almendras", "q": 25, "u": "g"}, {"n": "canela", "q": 1, "u": "cdta"}, {"n": "miel", "q": 1, "u": "cda"}]} $json$::jsonb);

-- ===========================
-- CENAS RÁPIDAS (55)
-- ===========================

-- C01
select seed_recipe($json$ {"nombre": "Tortilla de patatas a la sartén", "descripcion": "Tortilla de patatas jugosa con cebolla hecha en sartén.", "instrucciones": "Pela y corta las patatas y la cebolla en láminas finas\nPóchalas en la sartén con aceite unos 12 minutos\nEscurre y mezcla con los huevos batidos y la sal\nCuaja la tortilla por ambos lados a fuego medio", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 5, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C02
select seed_recipe($json$ {"nombre": "Salmón a la plancha con espárragos", "descripcion": "Lomos de salmón a la plancha con espárragos verdes salteados.", "instrucciones": "Salpimienta el salmón\nSaltea los espárragos en la plancha con aceite 6 minutos\nHaz el salmón 3-4 minutos por cada lado\nSirve con limón exprimido por encima", "raciones": 2, "prep_min": 5, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "primavera", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 300, "u": "g"}, {"n": "espárragos verdes", "q": 300, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C03
select seed_recipe($json$ {"nombre": "Merluza al horno con patatas panadera", "descripcion": "Lomos de merluza al horno sobre cama de patata y cebolla.", "instrucciones": "Corta las patatas y la cebolla en rodajas finas\nHornéalas 12 minutos a 220ºC con aceite y sal\nColoca la merluza encima y riega con el vino blanco\nHornea 8 minutos más y sirve con limón", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 350, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C04
select seed_recipe($json$ {"nombre": "Macarrones con atún y tomate", "descripcion": "Pasta de diario con sofrito de tomate, ajo y atún en conserva.", "instrucciones": "Cuece la pasta según el paquete\nDora el ajo laminado en una sartén con aceite\nAñade el tomate frito y el atún escurrido\nMezcla con la pasta y termina con orégano", "raciones": 2, "prep_min": 5, "cocina_min": 15, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "orégano", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C05
select seed_recipe($json$ {"nombre": "Ensalada de garbanzos veraniega", "descripcion": "Ensalada fría de garbanzos con tomate, pepino y pimiento.", "instrucciones": "Enjuaga y escurre los garbanzos\nPica el tomate, el pepino, el pimiento y la cebolla en dados\nMezcla todo en un bol grande\nAliña con aceite, vinagre y sal", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["rapida", "sin-horno", "veggie", "ensalada", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C06
select seed_recipe($json$ {"nombre": "Wraps de pollo con salsa de yogur", "descripcion": "Tortillas rellenas de pollo a la plancha, lechuga, tomate y yogur.", "instrucciones": "Corta la pechuga en tiras y hazla a la plancha con aceite y sal\nPica la lechuga y el tomate\nMezcla el yogur con una pizca de sal para la salsa\nRellena las tortillas, enrolla y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 10, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "yogur natural", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C07
select seed_recipe($json$ {"nombre": "Revuelto de gambas y espárragos", "descripcion": "Revuelto jugoso de gambas con espárragos verdes y ajo.", "instrucciones": "Trocea los espárragos y saltéalos con el ajo en aceite\nAñade las gambas y cocina 3 minutos\nIncorpora los huevos batidos con sal\nRemueve a fuego suave hasta que cuajen y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 12, "tags": ["rapida", "sin-horno"], "temporada": "primavera", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "huevo", "q": 4, "u": "pieza"}, {"n": "gambas", "q": 200, "u": "g"}, {"n": "espárragos verdes", "q": 200, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C08
select seed_recipe($json$ {"nombre": "Crema de calabaza con nata", "descripcion": "Crema suave de calabaza con un toque de nata para cocinar.", "instrucciones": "Sofríe la cebolla en la olla con aceite\nAñade la calabaza y la patata troceadas\nCubre con el caldo y cuece 18 minutos\nTritura con la nata y la sal hasta que quede fina", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie", "guiso"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabaza", "q": 600, "u": "g"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "nata para cocinar", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C09
select seed_recipe($json$ {"nombre": "Crema de calabacín con queso fresco", "descripcion": "Crema ligera de calabacín triturada con queso fresco.", "instrucciones": "Sofríe la cebolla en aceite\nAñade el calabacín y la patata troceados\nCubre con el caldo y cuece 15 minutos\nTritura con el queso fresco y la sal", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno", "veggie", "guiso"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabacín", "q": 2, "u": "pieza"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "queso fresco", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C10
select seed_recipe($json$ {"nombre": "Arroz salteado con huevo y verduras", "descripcion": "Arroz salteado estilo oriental con zanahoria, guisantes y huevo.", "instrucciones": "Cuece el arroz y escúrrelo\nSaltea la zanahoria en dados con aceite\nAñade los guisantes y el arroz y saltea 3 minutos\nHaz un hueco, cuaja los huevos y mezcla con la salsa de soja", "raciones": 2, "prep_min": 8, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 160, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "guisantes", "q": 100, "u": "g"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C11
select seed_recipe($json$ {"nombre": "Pollo al limón con arroz", "descripcion": "Pechuga de pollo salteada con salsa de limón y arroz blanco.", "instrucciones": "Cuece el arroz\nCorta la pechuga en dados y dórala con el ajo en aceite\nAñade el zumo de limón, el tomillo y la sal\nCocina 2 minutos más y sirve sobre el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C12
select seed_recipe($json$ {"nombre": "Hamburguesas caseras con ensalada", "descripcion": "Hamburguesas de carne picada en pan con ensalada fresca.", "instrucciones": "Forma dos hamburguesas con la carne salpimentada\nHazlas a la plancha 4 minutos por lado\nCorta la lechuga, el tomate y la cebolla\nMonta las hamburguesas en el pan con mostaza y la ensalada", "raciones": 2, "prep_min": 10, "cocina_min": 12, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "carne picada mixta", "q": 300, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C13
select seed_recipe($json$ {"nombre": "Espaguetis a la carbonara con nata", "descripcion": "Carbonara casera con bacon, nata y queso rallado.", "instrucciones": "Cuece la pasta según el paquete\nDora el bacon troceado en una sartén\nAñade la nata y el queso rallado y calienta 2 minutos\nMezcla con la pasta y termina con pimienta negra", "raciones": 2, "prep_min": 5, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "bacon", "q": 100, "u": "g"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "queso rallado", "q": 50, "u": "g"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C14
select seed_recipe($json$ {"nombre": "Dorada a la plancha con ensalada verde", "descripcion": "Lomos de dorada a la plancha con ensalada de lechuga y tomate.", "instrucciones": "Salpimienta la dorada\nHazla a la plancha con aceite 4 minutos por lado\nPrepara una ensalada con la lechuga y el tomate\nAliña todo con aceite, limón y sal", "raciones": 2, "prep_min": 8, "cocina_min": 12, "tags": ["rapida", "sin-horno", "ensalada"], "temporada": "verano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "dorada", "q": 500, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C15
select seed_recipe($json$ {"nombre": "Tacos rápidos de ternera", "descripcion": "Tortillas de trigo con carne picada especiada, maíz y queso.", "instrucciones": "Sofríe la cebolla y el pimiento en aceite\nAñade la carne picada con el comino y la sal\nIncorpora el maíz y cocina 3 minutos\nRellena las tortillas y termina con queso rallado", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "carne picada de ternera", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C16
select seed_recipe($json$ {"nombre": "Tofu salteado con brócoli y sésamo", "descripcion": "Salteado vegetal de tofu dorado con brócoli, soja y sésamo.", "instrucciones": "Corta el tofu en dados y dóralo en aceite\nAñade el brócoli en floretes y el ajo y saltea 8 minutos\nIncorpora la salsa de soja\nSirve con el sésamo espolvoreado", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno", "veggie", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "tofu", "q": 250, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C17
select seed_recipe($json$ {"nombre": "Gazpacho con picatostes", "descripcion": "Gazpacho fresquito triturado en cinco minutos con pan tostado.", "instrucciones": "Trocea el tomate, el pepino, el pimiento y el ajo\nTritura con aceite, vinagre, sal y un poco de agua fría\nCuela si lo quieres más fino y enfría\nSirve con picatostes de pan tostado", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "tomate", "q": 6, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C18
select seed_recipe($json$ {"nombre": "Tortilla de calabacín y cebolla", "descripcion": "Tortilla jugosa de calabacín pochado con cebolla.", "instrucciones": "Corta el calabacín y la cebolla en láminas finas\nPóchalos en la sartén con aceite 10 minutos\nMezcla con los huevos batidos y la sal\nCuaja la tortilla por ambos lados", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 5, "u": "pieza"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C19
select seed_recipe($json$ {"nombre": "Lomo a la plancha con pimientos", "descripcion": "Filetes de lomo de cerdo a la plancha con pimientos salteados.", "instrucciones": "Corta los pimientos en tiras\nSaltéalos con el ajo en aceite hasta que estén tiernos\nHaz los filetes de lomo a la plancha 3 minutos por lado\nSalpimienta y sirve todo junto", "raciones": 2, "prep_min": 8, "cocina_min": 18, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "lomo de cerdo", "q": 300, "u": "g"}, {"n": "pimiento verde", "q": 2, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C20
select seed_recipe($json$ {"nombre": "Ensalada César de pollo", "descripcion": "Ensalada templada de pollo a la plancha con picatostes y queso.", "instrucciones": "Haz la pechuga a la plancha y córtala en tiras\nTuesta el pan en dados para los picatostes\nMezcla la lechuga con el pollo y los picatostes\nAliña con aceite, limón, mostaza, sal y queso rallado", "raciones": 2, "prep_min": 12, "cocina_min": 12, "tags": ["rapida", "sin-horno", "ensalada"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "pechuga de pollo", "q": 250, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C21
select seed_recipe($json$ {"nombre": "Cuscús con verduras y garbanzos", "descripcion": "Cuscús rápido con salteado de verduras, garbanzos y comino.", "instrucciones": "Hidrata el cuscús con agua caliente y sal según el paquete\nSaltea la cebolla, la zanahoria y el calabacín en dados\nAñade los garbanzos y el comino y cocina 5 minutos\nMezcla con el cuscús y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno", "veggie", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "cuscús", "q": 150, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "garbanzos cocidos", "q": 200, "u": "g"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C22
select seed_recipe($json$ {"nombre": "Fideos salteados con gambas", "descripcion": "Fideos estilo wok con gambas, col, zanahoria y soja.", "instrucciones": "Cuece los fideos y escúrrelos\nSaltea el ajo, la zanahoria en juliana y la col en aceite\nAñade las gambas y cocina 3 minutos\nIncorpora los fideos y la salsa de soja y saltea 2 minutos", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "fideos", "q": 160, "u": "g"}, {"n": "gambas", "q": 200, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "col", "q": 200, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C23
select seed_recipe($json$ {"nombre": "Tostas caprese gratinadas", "descripcion": "Pan gratinado con tomate, mozzarella fundida y orégano.", "instrucciones": "Corta el pan en rebanadas y el tomate en rodajas\nMonta las tostas con tomate y mozzarella\nGratina en el horno 8 minutos a 200ºC\nTermina con orégano, aceite y sal", "raciones": 2, "prep_min": 8, "cocina_min": 10, "tags": ["rapida", "horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pan", "q": 4, "u": "pieza"}, {"n": "mozzarella", "q": 200, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C24
select seed_recipe($json$ {"nombre": "Quesadillas de pollo y queso", "descripcion": "Quesadillas doradas rellenas de pollo, pimiento y queso fundido.", "instrucciones": "Saltea la pechuga en tiras con la cebolla y el pimiento\nReparte el relleno y el queso sobre las tortillas\nDóblalas y dóralas en la sartén 2 minutos por lado\nCorta en triángulos y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "pechuga de pollo", "q": 250, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C25
select seed_recipe($json$ {"nombre": "Lentejas salteadas con chorizo", "descripcion": "Plato exprés de lentejas de bote salteadas con chorizo y pimentón.", "instrucciones": "Sofríe la cebolla y el ajo en aceite\nAñade el chorizo en rodajas y dóralo\nIncorpora las lentejas escurridas y el pimentón\nSaltea 5 minutos y rectifica de sal", "raciones": 2, "prep_min": 8, "cocina_min": 15, "tags": ["rapida", "sin-horno", "guiso", "fiambrera"], "temporada": "invierno", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 400, "u": "g"}, {"n": "chorizo", "q": 100, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C26
select seed_recipe($json$ {"nombre": "Sopa de fideos con pollo", "descripcion": "Sopa reconfortante de caldo de pollo con fideos y verduras.", "instrucciones": "Pon a hervir el caldo con la zanahoria y el puerro picados\nAñade la pechuga en dados y cuece 8 minutos\nIncorpora los fideos y cuece 5 minutos más\nRectifica de sal y sirve caliente", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno", "guiso"], "temporada": "invierno", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "caldo de pollo", "q": 800, "u": "ml"}, {"n": "fideos", "q": 100, "u": "g"}, {"n": "pechuga de pollo", "q": 150, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C27
select seed_recipe($json$ {"nombre": "Bacalao con tomate", "descripcion": "Lomos de bacalao cocinados en salsa de tomate casera.", "instrucciones": "Sofríe la cebolla y el ajo en aceite\nAñade el tomate triturado con el azúcar y la sal y cocina 10 minutos\nIncorpora el bacalao y cuece 8 minutos a fuego suave\nSirve con la salsa por encima", "raciones": 2, "prep_min": 8, "cocina_min": 22, "tags": ["rapida", "sin-horno", "guiso"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "bacalao", "q": 350, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "azúcar", "q": 5, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C28
select seed_recipe($json$ {"nombre": "Pavo al curry con leche de coco", "descripcion": "Dados de pavo en salsa cremosa de curry y leche de coco con arroz.", "instrucciones": "Cuece el arroz\nSofríe la cebolla y dora el pavo en dados con aceite\nAñade el curry y la leche de coco\nCocina 8 minutos a fuego suave y sirve con el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "filete de pavo", "q": 300, "u": "g"}, {"n": "leche de coco", "q": 200, "u": "ml"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C29
select seed_recipe($json$ {"nombre": "Ensalada de pasta con atún", "descripcion": "Ensalada fría de pasta con atún, maíz, tomate y aceitunas.", "instrucciones": "Cuece la pasta, escúrrela y refréscala con agua fría\nPica el tomate y mezcla con el atún, el maíz y las aceitunas\nAñade la pasta\nAliña con aceite, vinagre y sal", "raciones": 2, "prep_min": 10, "cocina_min": 12, "tags": ["rapida", "sin-horno", "ensalada", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 160, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "aceitunas", "q": 50, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C30
select seed_recipe($json$ {"nombre": "Pisto exprés con huevo", "descripcion": "Pisto rápido de verduras con tomate y huevo a la plancha.", "instrucciones": "Pica el calabacín, la berenjena, el pimiento y la cebolla en dados pequeños\nSaltéalos en aceite 12 minutos a fuego vivo\nAñade el tomate triturado y la sal y cocina 8 minutos\nHaz los huevos a la plancha y sirve encima del pisto", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie", "guiso", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "berenjena", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C31
select seed_recipe($json$ {"nombre": "Mejillones al vapor con vino blanco", "descripcion": "Mejillones abiertos al vapor con ajo, laurel y vino blanco.", "instrucciones": "Limpia los mejillones\nDora el ajo laminado en una olla grande\nAñade el vino blanco, el laurel y los mejillones y tapa\nCuece 5 minutos hasta que abran y sirve con limón y pan", "raciones": 2, "prep_min": 10, "cocina_min": 10, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "mejillones", "q": 1000, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}]} $json$::jsonb);

-- C32
select seed_recipe($json$ {"nombre": "Salchichas frescas con puré de patata", "descripcion": "Salchichas a la plancha con puré casero de patata y mantequilla.", "instrucciones": "Cuece las patatas peladas en trozos 15 minutos\nMachácalas con la leche caliente, la mantequilla y la sal\nHaz las salchichas a la plancha\nSirve las salchichas sobre el puré con un toque de pimienta", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "salchichas frescas", "q": 350, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "leche", "q": 100, "u": "ml"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C33
select seed_recipe($json$ {"nombre": "Boquerones enharinados con ensalada", "descripcion": "Boquerones fritos crujientes con ensalada de lechuga y limón.", "instrucciones": "Limpia los boquerones y sálalos\nPásalos por harina y fríelos en aceite caliente 2 minutos por lado\nEscúrrelos sobre papel de cocina\nSirve con la lechuga aliñada y limón", "raciones": 2, "prep_min": 12, "cocina_min": 12, "tags": ["rapida", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "boquerones", "q": 400, "u": "g"}, {"n": "harina de trigo", "q": 60, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C34
select seed_recipe($json$ {"nombre": "Sándwich caliente de atún y queso", "descripcion": "Sándwich tostado relleno de atún, tomate y queso fundido.", "instrucciones": "Mezcla el atún escurrido con la mostaza\nMonta los sándwiches con el atún, el tomate en rodajas y el queso\nUnta el exterior con mantequilla\nTuesta en la sartén hasta que el queso se funda", "raciones": 2, "prep_min": 8, "cocina_min": 8, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "pan de molde", "q": 4, "u": "pieza"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "mantequilla", "q": 20, "u": "g"}]} $json$::jsonb);

-- C35
select seed_recipe($json$ {"nombre": "Risotto rápido de champiñones", "descripcion": "Arroz cremoso con champiñones, vino blanco y queso rallado.", "instrucciones": "Sofríe la cebolla y los champiñones laminados en mantequilla\nAñade el arroz y tuéstalo 1 minuto\nVierte el vino y luego el caldo caliente poco a poco removiendo\nA los 18 minutos retira y manteca con el queso rallado", "raciones": 2, "prep_min": 5, "cocina_min": 25, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "otono", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 160, "u": "g"}, {"n": "champiñones", "q": 250, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "vino blanco", "q": 50, "u": "ml"}, {"n": "queso rallado", "q": 50, "u": "g"}, {"n": "mantequilla", "q": 20, "u": "g"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C36
select seed_recipe($json$ {"nombre": "Calamares a la plancha con ajo y limón", "descripcion": "Calamares a la plancha con majado de ajo, aceite y limón.", "instrucciones": "Cuece las patatas en rodajas 12 minutos\nHaz los calamares a la plancha a fuego fuerte 2-3 minutos por lado\nPrepara un aliño con ajo picado, aceite y zumo de limón\nSirve los calamares y las patatas con el aliño y sal", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "calamares", "q": 400, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C37
select seed_recipe($json$ {"nombre": "Burritos de soja texturizada", "descripcion": "Burritos veganos de soja texturizada con tomate y comino.", "instrucciones": "Hidrata la soja texturizada en agua caliente 10 minutos y escurre\nSofríe la cebolla en aceite y añade la soja con el comino\nIncorpora el tomate frito y cocina 5 minutos\nRellena las tortillas con la mezcla y el queso y enrolla", "raciones": 2, "prep_min": 12, "cocina_min": 15, "tags": ["rapida", "sin-horno", "veggie", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "soja texturizada", "q": 100, "u": "g"}, {"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C38
select seed_recipe($json$ {"nombre": "Crema de puerro y patata", "descripcion": "Crema casera tipo vichyssoise servida caliente.", "instrucciones": "Sofríe el puerro y la cebolla picados en aceite\nAñade la patata troceada y el caldo\nCuece 18 minutos\nTritura con la nata y la sal hasta que quede fina", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie", "guiso"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "puerro", "q": 2, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "nata para cocinar", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C39
select seed_recipe($json$ {"nombre": "Pollo al ajillo rápido", "descripcion": "Muslos de pollo troceados al ajillo con vino blanco y laurel.", "instrucciones": "Trocea el pollo y sálalo\nDóralo en aceite a fuego fuerte 8 minutos\nAñade los ajos laminados y el laurel y dora 2 minutos\nVierte el vino blanco y reduce 8 minutos a fuego medio", "raciones": 2, "prep_min": 8, "cocina_min": 22, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 450, "u": "g"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C40
select seed_recipe($json$ {"nombre": "Ensalada griega", "descripcion": "Ensalada fresca de tomate, pepino, feta y aceitunas con orégano.", "instrucciones": "Corta el tomate y el pepino en trozos grandes\nCorta la cebolla en plumas finas\nAñade el queso feta en dados y las aceitunas\nAliña con aceite, orégano y sal", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["rapida", "sin-horno", "veggie", "ensalada"], "temporada": "verano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 150, "u": "g"}, {"n": "aceitunas", "q": 60, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C41
select seed_recipe($json$ {"nombre": "Huevos rotos con jamón serrano", "descripcion": "Patatas fritas en dados con huevos rotos y jamón serrano.", "instrucciones": "Corta las patatas en dados y fríelas en aceite hasta dorar\nEscúrrelas y sálalas\nHaz los huevos a la plancha dejando la yema líquida\nSirve los huevos sobre las patatas, rómpelos y añade el jamón", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "patata", "q": 3, "u": "pieza"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "jamón serrano", "q": 80, "u": "g"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C42
select seed_recipe($json$ {"nombre": "Wok de pollo con brócoli y zanahoria", "descripcion": "Salteado oriental de pollo con brócoli, zanahoria, soja y sésamo.", "instrucciones": "Corta la pechuga en tiras y saltéala en aceite a fuego fuerte\nAñade el brócoli en floretes pequeños y la zanahoria en juliana\nSaltea 8 minutos con el ajo picado\nIncorpora la salsa de soja y el sésamo y sirve", "raciones": 2, "prep_min": 12, "cocina_min": 15, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- C43
select seed_recipe($json$ {"nombre": "Tortilla de espinacas y queso feta", "descripcion": "Tortilla esponjosa con espinacas salteadas y queso feta.", "instrucciones": "Sofríe la cebolla picada en aceite\nAñade las espinacas y saltea hasta que pierdan el agua\nMezcla con los huevos batidos, el feta desmenuzado y la sal\nCuaja la tortilla por ambos lados a fuego medio", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 5, "u": "pieza"}, {"n": "espinacas", "q": 200, "u": "g"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C44
select seed_recipe($json$ {"nombre": "Salmón al horno con brócoli", "descripcion": "Bandeja de horno con salmón, brócoli, limón y tomillo.", "instrucciones": "Precalienta el horno a 200ºC\nColoca el salmón y el brócoli en floretes en una bandeja\nAliña con aceite, tomillo, sal y rodajas de limón\nHornea 18 minutos y sirve", "raciones": 2, "prep_min": 8, "cocina_min": 20, "tags": ["rapida", "horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 300, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C45
select seed_recipe($json$ {"nombre": "Albóndigas rápidas en salsa de tomate", "descripcion": "Albóndigas caseras doradas y terminadas en salsa de tomate.", "instrucciones": "Mezcla la carne con el huevo, el pan rallado, el ajo picado y la sal\nForma albóndigas pequeñas\nDóralas en aceite por todos los lados\nAñade el tomate frito y cocina 8 minutos a fuego suave", "raciones": 2, "prep_min": 12, "cocina_min": 18, "tags": ["rapida", "sin-horno", "guiso", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "carne picada mixta", "q": 350, "u": "g"}, {"n": "pan rallado", "q": 30, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomate frito", "q": 300, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C46
select seed_recipe($json$ {"nombre": "Coliflor gratinada con bechamel", "descripcion": "Coliflor cocida y gratinada con bechamel rápida y queso.", "instrucciones": "Cuece la coliflor en floretes 10 minutos y escurre\nHaz una bechamel con la mantequilla, la harina y la leche\nMezcla la coliflor con la bechamel en una fuente\nCubre con queso rallado y gratina 8 minutos", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "horno", "veggie"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "coliflor", "q": 1, "u": "pieza"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "harina de trigo", "q": 30, "u": "g"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C47
select seed_recipe($json$ {"nombre": "Bol de arroz con atún y aguacate", "descripcion": "Bol templado de arroz con atún, aguacate, pepino y sésamo.", "instrucciones": "Cuece el arroz y deja templar\nCorta el aguacate y el pepino en dados\nMonta los boles con el arroz, el atún escurrido y las verduras\nAliña con salsa de soja y sésamo", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "arroz", "q": 150, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}]} $json$::jsonb);

-- C48
select seed_recipe($json$ {"nombre": "Sopa de tomate con picatostes", "descripcion": "Sopa casera de tomate con ajo, orégano y pan tostado.", "instrucciones": "Sofríe la cebolla y el ajo picados en aceite\nAñade el tomate triturado y cocina 8 minutos\nVierte el caldo y cuece 10 minutos más con sal y orégano\nTritura y sirve con picatostes de pan tostado", "raciones": 2, "prep_min": 8, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie", "guiso"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "tomate triturado", "q": 600, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "caldo de verduras", "q": 400, "u": "ml"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C49
select seed_recipe($json$ {"nombre": "Filetes de pavo empanados con ensalada", "descripcion": "Filetes de pavo crujientes empanados con ensalada fresca.", "instrucciones": "Salpimienta los filetes de pavo\nPásalos por huevo batido y pan rallado\nFríelos en aceite 3 minutos por lado hasta dorar\nSirve con ensalada de lechuga y tomate", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "filete de pavo", "q": 300, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "pan rallado", "q": 80, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C50
select seed_recipe($json$ {"nombre": "Garbanzos con espinacas", "descripcion": "Clásico salteado andaluz de garbanzos, espinacas y pimentón.", "instrucciones": "Dora los ajos laminados en aceite\nAñade las espinacas y saltea hasta que reduzcan\nIncorpora los garbanzos escurridos, el pimentón y el comino\nSaltea 5 minutos, sala y sirve", "raciones": 2, "prep_min": 8, "cocina_min": 15, "tags": ["rapida", "sin-horno", "veggie", "guiso", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "espinacas", "q": 250, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C51
select seed_recipe($json$ {"nombre": "Pasta cremosa de calabacín", "descripcion": "Pasta con salsa cremosa de calabacín salteado, nata y queso.", "instrucciones": "Cuece la pasta según el paquete\nSaltea el calabacín en dados con el ajo en aceite\nAñade la nata y el queso rallado y cocina 3 minutos\nMezcla con la pasta y rectifica de sal", "raciones": 2, "prep_min": 8, "cocina_min": 18, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 170, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "nata para cocinar", "q": 150, "u": "ml"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C52
select seed_recipe($json$ {"nombre": "Ensalada templada de quinoa", "descripcion": "Quinoa con verduras salteadas, queso feta y aliño de limón.", "instrucciones": "Cuece la quinoa 15 minutos y escurre\nSaltea el calabacín y el pimiento en dados con aceite\nMezcla la quinoa con las verduras y el feta desmenuzado\nAliña con zumo de limón, aceite y sal", "raciones": 2, "prep_min": 10, "cocina_min": 18, "tags": ["rapida", "sin-horno", "veggie", "ensalada", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "quinoa", "q": 140, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C53
select seed_recipe($json$ {"nombre": "Arroz a la cubana", "descripcion": "Arroz blanco con tomate frito, huevo a la plancha y plátano.", "instrucciones": "Cuece el arroz con el ajo y escúrrelo\nCalienta el tomate frito\nHaz los huevos a la plancha y dora el plátano en rodajas\nMonta el plato con el arroz, el tomate, el huevo y el plátano", "raciones": 2, "prep_min": 8, "cocina_min": 20, "tags": ["rapida", "sin-horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 160, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "plátano", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C54
select seed_recipe($json$ {"nombre": "Berenjenas rellenas exprés", "descripcion": "Berenjenas al microondas rellenas de carne con tomate y gratinadas.", "instrucciones": "Corta las berenjenas por la mitad y hazlas 8 minutos al microondas\nVacía la pulpa y pícala\nSofríe la cebolla, la carne y la pulpa, y añade el tomate frito y la sal\nRellena las berenjenas, cubre con queso y gratina 8 minutos", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "berenjena", "q": 2, "u": "pieza"}, {"n": "carne picada de ternera", "q": 250, "u": "g"}, {"n": "tomate frito", "q": 150, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

-- C55
select seed_recipe($json$ {"nombre": "Alcachofas salteadas con jamón y huevo", "descripcion": "Corazones de alcachofa salteados con jamón serrano y huevo a la plancha.", "instrucciones": "Limpia las alcachofas y córtalas en cuartos\nSaltéalas con el ajo en aceite 12 minutos hasta dorar\nAñade el jamón serrano troceado y saltea 2 minutos\nHaz los huevos a la plancha y sirve encima con sal", "raciones": 2, "prep_min": 12, "cocina_min": 18, "tags": ["rapida", "sin-horno"], "temporada": "primavera", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "alcachofa", "q": 6, "u": "pieza"}, {"n": "jamón serrano", "q": 80, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select validate_seed_recipes();
