-- Lote 2: comidas de diario, guisos, batch y fiambrera (85 recetas)

-- 1
select seed_recipe($json$ {"nombre": "Lentejas con verduras de la huerta", "descripcion": "Guiso clásico de lentejas con sofrito y verduras de temporada.", "instrucciones": "Sofríe la cebolla, el ajo y el pimiento picados en aceite\nAñade la zanahoria y la patata en trozos junto con las lentejas\nIncorpora el pimentón y el laurel y cubre con el caldo\nCuece a fuego medio 35 minutos hasta que la lenteja esté tierna\nRectifica de sal y deja reposar 5 minutos", "raciones": 4, "prep_min": 15, "cocina_min": 40, "tags": ["guiso", "batch", "veggie", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 1200, "u": "ml"}] } $json$::jsonb);

-- 2
select seed_recipe($json$ {"nombre": "Lentejas estofadas con chorizo", "descripcion": "Lentejas de toda la vida con chorizo y pimentón, contundentes y sabrosas.", "instrucciones": "Sofríe cebolla y ajo en aceite hasta dorar\nAñade el chorizo en rodajas y dale unas vueltas\nIncorpora lentejas, patata, pimentón y laurel y cubre con caldo\nCuece 35-40 minutos a fuego suave y sala al gusto", "raciones": 4, "prep_min": 15, "cocina_min": 40, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 300, "u": "g"}, {"n": "chorizo", "q": 150, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "caldo de pollo", "q": 1200, "u": "ml"}] } $json$::jsonb);

-- 3
select seed_recipe($json$ {"nombre": "Potaje de garbanzos con espinacas", "descripcion": "Potaje tradicional de garbanzos y espinacas con huevo duro.", "instrucciones": "Cuece los huevos 10 minutos, pela y reserva\nSofríe cebolla, ajo, pimentón y comino en aceite\nAñade los garbanzos, la patata en trozos y agua hasta cubrir\nCuece 20 minutos, agrega las espinacas y cocina 5 minutos más\nSirve con el huevo duro en cuartos", "raciones": 4, "prep_min": 15, "cocina_min": 30, "tags": ["guiso", "batch", "veggie", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 800, "u": "g"}, {"n": "espinacas", "q": 300, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 4
select seed_recipe($json$ {"nombre": "Garbanzos con bacalao al estilo de vigilia", "descripcion": "Potaje de cuaresma con garbanzos, bacalao desmigado y espinacas.", "instrucciones": "Sofríe la cebolla y el ajo con el pimentón\nAñade los garbanzos y agua hasta casi cubrir\nIncorpora el bacalao en trozos y las espinacas y cuece 10 minutos\nAñade el huevo duro picado, rectifica de sal y sirve caliente", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "bacalao", "q": 250, "u": "g"}, {"n": "espinacas", "q": 200, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 5
select seed_recipe($json$ {"nombre": "Alubias blancas con chorizo a la asturiana", "descripcion": "Versión exprés de la fabada con alubias cocidas y chorizo.", "instrucciones": "Sofríe la cebolla y el ajo en el aceite\nAñade el chorizo en rodajas gruesas y dóralo\nIncorpora las alubias, la patata, el pimentón y el laurel con el caldo\nCuece 20 minutos a fuego suave para que espese y sala al gusto", "raciones": 4, "prep_min": 10, "cocina_min": 30, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "legumbre", "ingredientes": [{"n": "alubias blancas cocidas", "q": 800, "u": "g"}, {"n": "chorizo", "q": 200, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "caldo de pollo", "q": 500, "u": "ml"}] } $json$::jsonb);

-- 6
select seed_recipe($json$ {"nombre": "Alubias blancas con verduras y comino", "descripcion": "Guiso ligero de alubias con calabacín, zanahoria y puerro.", "instrucciones": "Pocha el puerro y la zanahoria picados en el aceite\nAñade el calabacín en dados y el tomate triturado\nIncorpora las alubias y el comino y cuece 15 minutos\nRectifica de sal y sirve con un chorrito de aceite crudo", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["guiso", "veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "alubias blancas cocidas", "q": 500, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 7
select seed_recipe($json$ {"nombre": "Lentejas al curry con leche de coco y arroz", "descripcion": "Dahl cremoso de lentejas al curry servido sobre arroz blanco.", "instrucciones": "Sofríe la cebolla y el ajo con el curry\nAñade las lentejas, el tomate triturado y la leche de coco con un vaso de agua\nCuece 25 minutos removiendo de vez en cuando\nCuece el arroz aparte 15 minutos y escurre\nSirve las lentejas sobre el arroz", "raciones": 4, "prep_min": 10, "cocina_min": 35, "tags": ["guiso", "batch", "veggie", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 300, "u": "g"}, {"n": "leche de coco", "q": 400, "u": "ml"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "arroz", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 8
select seed_recipe($json$ {"nombre": "Cocido exprés de garbanzos con pollo", "descripcion": "Cocido rápido con garbanzos de bote, pollo y sopa de fideos.", "instrucciones": "Cuece el muslo de pollo con el caldo, la zanahoria, el apio y la patata 20 minutos\nAñade los garbanzos y cuece 10 minutos más\nRetira parte del caldo y cuece en él los fideos 5 minutos\nSirve primero la sopa y después los garbanzos con el pollo desmenuzado", "raciones": 4, "prep_min": 15, "cocina_min": 40, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "garbanzos cocidos", "q": 800, "u": "g"}, {"n": "muslo de pollo", "q": 400, "u": "g"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "apio", "q": 1, "u": "pieza"}, {"n": "fideos", "q": 100, "u": "g"}, {"n": "caldo de pollo", "q": 1500, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 9
select seed_recipe($json$ {"nombre": "Garbanzos guisados con calabaza y pimentón", "descripcion": "Guiso otoñal de garbanzos con calabaza dulce y toque ahumado.", "instrucciones": "Sofríe la cebolla y el ajo en aceite\nAñade la calabaza en dados y el pimentón y rehoga 5 minutos\nIncorpora el tomate triturado y los garbanzos con medio vaso de agua\nCuece 15 minutos hasta que la calabaza esté tierna y sala", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["guiso", "veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "calabaza", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 10
select seed_recipe($json$ {"nombre": "Estofado de ternera con patatas", "descripcion": "Ternera guisada a fuego lento con patatas, zanahoria y guisantes.", "instrucciones": "Dora la ternera en aceite y reserva\nSofríe cebolla, ajo y zanahoria en la misma olla\nDevuelve la carne, añade el vino y deja evaporar\nAgrega caldo, laurel y cuece 50 minutos a fuego suave\nIncorpora las patatas y los guisantes y cuece 20 minutos más", "raciones": 4, "prep_min": 20, "cocina_min": 75, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "ternera para guisar", "q": 600, "u": "g"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "guisantes", "q": 150, "u": "g"}, {"n": "vino blanco", "q": 150, "u": "ml"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "caldo de pollo", "q": 600, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 11
select seed_recipe($json$ {"nombre": "Guiso de pollo a la jardinera", "descripcion": "Pollo guisado con patatas, judías verdes y guisantes en salsa ligera.", "instrucciones": "Dora los muslos de pollo salpimentados en aceite\nAñade la cebolla picada y la zanahoria y sofríe\nVierte el vino, deja reducir y cubre con caldo\nCuece 25 minutos, añade patatas, judías verdes y guisantes\nCocina 20 minutos más hasta que todo esté tierno", "raciones": 4, "prep_min": 15, "cocina_min": 55, "tags": ["guiso", "batch", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 800, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "judías verdes", "q": 200, "u": "g"}, {"n": "guisantes", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "caldo de pollo", "q": 600, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 12
select seed_recipe($json$ {"nombre": "Marmitako de salmón", "descripcion": "Guiso marinero de patatas con salmón, pimiento y pimentón.", "instrucciones": "Sofríe cebolla, ajo y pimiento verde picados\nAñade el pimentón, el tomate triturado y las patatas chascadas\nCubre con caldo y cuece 20 minutos\nIncorpora el salmón en tacos, apaga el fuego y deja que se haga 5 minutos con el calor residual", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["guiso", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 300, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 13
select seed_recipe($json$ {"nombre": "Patatas a la riojana", "descripcion": "Patatas chascadas guisadas con chorizo y pimentón.", "instrucciones": "Sofríe la cebolla, el ajo y el pimiento rojo picados\nAñade el chorizo en rodajas y rehoga 2 minutos\nIncorpora las patatas chascadas, el pimentón y el laurel\nCubre con caldo y cuece 25 minutos hasta que la salsa espese\nRectifica de sal y reposa 5 minutos", "raciones": 4, "prep_min": 15, "cocina_min": 35, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "patata", "ingredientes": [{"n": "patata", "q": 6, "u": "pieza"}, {"n": "chorizo", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "caldo de pollo", "q": 1000, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 14
select seed_recipe($json$ {"nombre": "Estofado de pavo con zanahorias", "descripcion": "Pavo tierno guisado con zanahoria, patata y tomillo.", "instrucciones": "Dora el pavo en dados en el aceite\nAñade la cebolla picada y las zanahorias en rodajas\nVierte el vino blanco y deja reducir\nIncorpora la patata en trozos, el tomillo y agua hasta casi cubrir\nCuece 25 minutos y rectifica de sal", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["guiso", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "filete de pavo", "q": 300, "u": "g"}, {"n": "zanahoria", "q": 3, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 15
select seed_recipe($json$ {"nombre": "Magro de cerdo con tomate y patatas", "descripcion": "Tacos de lomo en salsa de tomate casera con patatas.", "instrucciones": "Dora el lomo en dados en el aceite y reserva\nSofríe cebolla, ajo y pimiento verde picados\nDevuelve la carne, añade el tomate frito y el orégano\nCuece 20 minutos a fuego suave\nFríe o asa las patatas en gajos y sirve de guarnición", "raciones": 4, "prep_min": 15, "cocina_min": 35, "tags": ["guiso", "batch", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "cerdo", "ingredientes": [{"n": "lomo de cerdo", "q": 600, "u": "g"}, {"n": "tomate frito", "q": 400, "u": "g"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 16
select seed_recipe($json$ {"nombre": "Guiso de calamares con patatas y guisantes", "descripcion": "Calamares tiernos guisados con patatas en salsa de pimentón.", "instrucciones": "Sofríe la cebolla y el ajo picados en aceite\nAñade los calamares en anillas y rehoga 5 minutos\nVierte el vino blanco y deja evaporar\nIncorpora las patatas chascadas, el pimentón y agua hasta cubrir\nCuece 25 minutos y añade los guisantes los últimos 5", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "calamares", "q": 400, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "guisantes", "q": 100, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 17
select seed_recipe($json$ {"nombre": "Caldereta de merluza con patatas", "descripcion": "Merluza en guiso suave con patatas, pimiento y vino blanco.", "instrucciones": "Sofríe la cebolla, el ajo y el pimiento rojo\nAñade el pimentón y las patatas en rodajas gruesas\nVierte el vino y agua hasta cubrir y cuece 20 minutos\nColoca la merluza encima, tapa y cocina 6-8 minutos\nSala y sirve con el caldito del guiso", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 350, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 18
select seed_recipe($json$ {"nombre": "Salchichas frescas guisadas con patatas", "descripcion": "Salchichas doradas y guisadas con patatas en salsa de vino blanco.", "instrucciones": "Dora las salchichas en el aceite y resérvalas\nSofríe la cebolla y la zanahoria picadas\nDevuelve las salchichas, añade el vino y el laurel\nIncorpora las patatas en trozos y agua hasta casi cubrir\nCuece 25 minutos hasta que la patata esté tierna", "raciones": 2, "prep_min": 10, "cocina_min": 35, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "salchichas frescas", "q": 250, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 19
select seed_recipe($json$ {"nombre": "Estofado de soja texturizada con verduras", "descripcion": "Guiso vegetal contundente con soja texturizada, patata y champiñones.", "instrucciones": "Hidrata la soja texturizada en agua caliente 10 minutos\nSofríe cebolla, ajo y zanahoria en aceite\nAñade los champiñones laminados y la soja escurrida\nIncorpora tomate triturado, pimentón, patata en dados y un vaso de agua\nCuece 20 minutos y rectifica de sal", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["guiso", "veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "soja texturizada", "q": 120, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "champiñones", "q": 150, "u": "g"}, {"n": "tomate triturado", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 20
select seed_recipe($json$ {"nombre": "Pollo al vino blanco con champiñones", "descripcion": "Muslos de pollo guisados con champiñones, vino y patatas.", "instrucciones": "Dora los muslos salpimentados en el aceite\nAñade la cebolla y el ajo picados y pocha\nIncorpora los champiñones y el tomillo y saltea\nVierte el vino, deja reducir y añade las patatas con agua hasta media altura\nCuece tapado 35 minutos hasta que el pollo esté tierno", "raciones": 4, "prep_min": 15, "cocina_min": 50, "tags": ["guiso", "batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 800, "u": "g"}, {"n": "champiñones", "q": 300, "u": "g"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "vino blanco", "q": 200, "u": "ml"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 21
select seed_recipe($json$ {"nombre": "Crema de calabaza con garbanzos especiados", "descripcion": "Crema suave de calabaza coronada con garbanzos salteados al pimentón.", "instrucciones": "Pocha el puerro en aceite y añade la calabaza y la patata en trozos\nCubre con agua, sala y cuece 20 minutos\nTritura con la nata hasta obtener una crema fina\nSaltea los garbanzos con pimentón y comino hasta dorarlos\nSirve la crema con los garbanzos por encima", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["veggie", "sin-horno", "guiso"], "temporada": "otono", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabaza", "q": 600, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "garbanzos cocidos", "q": 300, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 22
select seed_recipe($json$ {"nombre": "Sopa de cocido con fideos y garbanzos", "descripcion": "Sopa completa de caldo de pollo con fideos, garbanzos y verdura.", "instrucciones": "Cuece el muslo de pollo en el caldo con la zanahoria y el apio 20 minutos\nRetira el pollo, desmenúzalo y devuélvelo a la olla\nAñade los garbanzos y los fideos\nCuece 5-6 minutos más y rectifica de sal", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "fideos", "q": 120, "u": "g"}, {"n": "garbanzos cocidos", "q": 300, "u": "g"}, {"n": "muslo de pollo", "q": 200, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "apio", "q": 1, "u": "pieza"}, {"n": "caldo de pollo", "q": 1200, "u": "ml"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 23
select seed_recipe($json$ {"nombre": "Arroz con pollo casero", "descripcion": "Arroz dorado con muslos de pollo, pimiento y sofrito de tomate.", "instrucciones": "Dora los muslos troceados en aceite y reserva\nSofríe el ajo y el pimiento rojo, añade el tomate triturado y el pimentón\nIncorpora el arroz y dale unas vueltas\nDevuelve el pollo, vierte el caldo caliente y cuece 18 minutos\nDeja reposar 5 minutos tapado antes de servir", "raciones": 4, "prep_min": 15, "cocina_min": 40, "tags": ["batch", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "arroz", "q": 350, "u": "g"}, {"n": "muslo de pollo", "q": 600, "u": "g"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de pollo", "q": 900, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 24
select seed_recipe($json$ {"nombre": "Paella rápida de marisco", "descripcion": "Arroz de marisco con gambas, mejillones y calamares en sartén grande.", "instrucciones": "Sofríe el ajo y el pimiento rojo en aceite\nAñade los calamares y saltea 3 minutos\nIncorpora el tomate triturado, el pimentón y el arroz\nVierte el caldo caliente y cuece 15 minutos sin remover\nReparte gambas y mejillones encima y cocina 5 minutos más", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "gambas", "q": 150, "u": "g"}, {"n": "mejillones", "q": 200, "u": "g"}, {"n": "calamares", "q": 150, "u": "g"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 150, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 25
select seed_recipe($json$ {"nombre": "Arroz a la cubana con plátano", "descripcion": "Arroz blanco con tomate frito, huevo frito y plátano dorado.", "instrucciones": "Cuece el arroz con el ajo 15 minutos y escurre\nCalienta el tomate frito\nFríe los huevos y dora el plátano en rodajas en la misma sartén\nMonta el plato con el arroz, el tomate, el huevo y el plátano", "raciones": 2, "prep_min": 5, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "plátano", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 26
select seed_recipe($json$ {"nombre": "Arroz tres delicias con jamón", "descripcion": "Arroz salteado estilo oriental con jamón cocido, huevo y guisantes.", "instrucciones": "Cuece el arroz 15 minutos, escurre y deja enfriar\nHaz una tortilla francesa con los huevos y trocéala\nSaltea la zanahoria en daditos con los guisantes y el maíz\nAñade el arroz, el jamón en tacos y la tortilla\nRiega con la salsa de soja y saltea 2 minutos a fuego fuerte", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["fiambrera", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "jamón cocido", "q": 100, "u": "g"}, {"n": "guisantes", "q": 100, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 27
select seed_recipe($json$ {"nombre": "Risotto de champiñones", "descripcion": "Risotto cremoso de champiñones con queso y mantequilla.", "instrucciones": "Pocha la cebolla en aceite y añade los champiñones laminados\nIncorpora el arroz y tuéstalo 2 minutos\nVierte el vino y deja evaporar\nAñade el caldo caliente poco a poco removiendo 18 minutos\nFuera del fuego liga con la mantequilla y el queso rallado", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "champiñones", "q": 250, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 700, "u": "ml"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 28
select seed_recipe($json$ {"nombre": "Arroz con calamares", "descripcion": "Arroz meloso con calamares y sofrito de tomate y pimiento.", "instrucciones": "Sofríe la cebolla, el ajo y el pimiento verde\nAñade los calamares en anillas y saltea 5 minutos\nIncorpora el tomate triturado y el vino y deja reducir\nAgrega el arroz y el caldo caliente y cuece 18 minutos\nReposa 5 minutos antes de servir", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "calamares", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 29
select seed_recipe($json$ {"nombre": "Arroz al horno con garbanzos y patata", "descripcion": "Arroz al horno valenciano en versión vegetal con garbanzos.", "instrucciones": "Precalienta el horno a 200 grados\nSofríe el ajo, el tomate en rodajas y la patata en una cazuela apta para horno\nAñade el arroz, los garbanzos y el pimentón\nVierte el caldo hirviendo y hornea 25 minutos sin remover\nDeja reposar 5 minutos antes de servir", "raciones": 4, "prep_min": 15, "cocina_min": 35, "tags": ["horno", "batch", "veggie"], "temporada": "invierno", "batch_days": 2, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 350, "u": "g"}, {"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 800, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 30
select seed_recipe($json$ {"nombre": "Salteado de arroz con verduras y huevo", "descripcion": "Arroz salteado al wok con brócoli, calabacín y toque de soja.", "instrucciones": "Cuece el arroz 15 minutos y escurre\nSaltea el brócoli, la zanahoria y el calabacín en daditos a fuego fuerte\nAparta las verduras y cuaja los huevos batidos en la sartén\nAñade el arroz, la salsa de soja y el sésamo\nSaltea todo junto 3 minutos y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["veggie", "fiambrera", "sin-horno", "rapida"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "brócoli", "q": 150, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 31
select seed_recipe($json$ {"nombre": "Ensalada de arroz veraniega con atún", "descripcion": "Arroz frío con atún, tomate, pepino, maíz y aceitunas.", "instrucciones": "Cuece el arroz 15 minutos, escurre y enfría bajo el grifo\nTrocea el tomate y el pepino en dados\nMezcla el arroz con el atún escurrido, el maíz y las aceitunas\nAliña con aceite, vinagre y sal y enfría en la nevera", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["ensalada", "fiambrera", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "arroz", "q": 160, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "aceitunas", "q": 50, "u": "g"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 32
select seed_recipe($json$ {"nombre": "Arroz caldoso con mejillones", "descripcion": "Arroz marinero caldoso con mejillones y sofrito de pimentón.", "instrucciones": "Sofríe la cebolla y el ajo en aceite\nAñade el tomate triturado y el pimentón y cocina 5 minutos\nVierte el vino, el caldo y lleva a ebullición\nAgrega el arroz y cuece 16 minutos\nIncorpora los mejillones limpios y cuece 4 minutos hasta que se abran", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "mejillones", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 1000, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 33
select seed_recipe($json$ {"nombre": "Arroz con curry de pollo y leche de coco", "descripcion": "Curry suave de pollo con leche de coco servido con arroz blanco.", "instrucciones": "Sofríe la cebolla y el ajo con el curry en aceite\nAñade la pechuga en tacos y dora 5 minutos\nVierte la leche de coco y cuece 15 minutos a fuego suave\nCuece el arroz aparte 15 minutos y escurre\nSirve el curry sobre el arroz", "raciones": 4, "prep_min": 10, "cocina_min": 30, "tags": ["batch", "fiambrera", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "arroz", "q": 350, "u": "g"}, {"n": "pechuga de pollo", "q": 500, "u": "g"}, {"n": "leche de coco", "q": 400, "u": "ml"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 34
select seed_recipe($json$ {"nombre": "Arroz con salchichas y tomate", "descripcion": "Arroz meloso con salchichas frescas doradas y salsa de tomate.", "instrucciones": "Dora las salchichas troceadas en el aceite y reserva\nSofríe la cebolla en la misma cazuela\nAñade el tomate frito, el orégano y el arroz\nDevuelve las salchichas, vierte el caldo caliente y cuece 18 minutos\nDeja reposar 5 minutos antes de servir", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "salchichas frescas", "q": 200, "u": "g"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "caldo de pollo", "q": 500, "u": "ml"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 35
select seed_recipe($json$ {"nombre": "Risotto de calabaza y queso", "descripcion": "Risotto otoñal de calabaza asada con queso rallado y tomillo.", "instrucciones": "Pocha la cebolla en aceite y añade la calabaza en daditos\nIncorpora el arroz y tuéstalo 2 minutos\nAñade el caldo caliente poco a poco removiendo 18 minutos\nFuera del fuego liga con mantequilla y queso rallado\nTermina con tomillo y pimienta", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "calabaza", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "mantequilla", "q": 25, "u": "g"}, {"n": "caldo de verduras", "q": 700, "u": "ml"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 36
select seed_recipe($json$ {"nombre": "Arroz con bacalao y coliflor", "descripcion": "Arroz tradicional de cuaresma con bacalao desmigado y coliflor.", "instrucciones": "Sofríe los ajos laminados con el pimentón\nAñade el tomate triturado y la coliflor en ramitos pequeños\nIncorpora el arroz y el caldo caliente\nCuece 12 minutos y añade el bacalao desmigado\nCocina 6 minutos más y deja reposar tapado", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "bacalao", "q": 250, "u": "g"}, {"n": "coliflor", "q": 300, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "tomate triturado", "q": 150, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 37
select seed_recipe($json$ {"nombre": "Fideuá de gambas", "descripcion": "Fideos dorados al estilo fideuá con gambas y alioli opcional.", "instrucciones": "Dora los fideos en el aceite y reserva\nSofríe el ajo, añade el tomate triturado y el pimentón\nIncorpora los fideos y el caldo hirviendo\nCuece 8 minutos y reparte las gambas por encima\nCocina 3 minutos más hasta que el fideo quede de pie", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "fideos", "q": 200, "u": "g"}, {"n": "gambas", "q": 200, "u": "g"}, {"n": "tomate triturado", "q": 150, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 38
select seed_recipe($json$ {"nombre": "Macarrones con atún", "descripcion": "Clásico de fiambrera: macarrones con tomate, atún y queso.", "instrucciones": "Cuece la pasta según el paquete y escurre\nSofríe la cebolla picada en aceite\nAñade el tomate frito, el orégano y el atún escurrido\nMezcla con la pasta y sirve con queso rallado por encima", "raciones": 2, "prep_min": 5, "cocina_min": 20, "tags": ["fiambrera", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "tomate frito", "q": 250, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}] } $json$::jsonb);

-- 39
select seed_recipe($json$ {"nombre": "Espaguetis a la boloñesa", "descripcion": "Espaguetis con salsa boloñesa de ternera cocinada a fuego lento.", "instrucciones": "Sofríe cebolla, ajo y zanahoria muy picados\nAñade la carne picada y dórala desmenuzándola\nVierte el vino y deja evaporar\nIncorpora el tomate triturado y el orégano y cuece 25 minutos\nCuece la pasta, escurre y mezcla con la salsa", "raciones": 4, "prep_min": 15, "cocina_min": 40, "tags": ["batch", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 350, "u": "g"}, {"n": "carne picada de ternera", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 40
select seed_recipe($json$ {"nombre": "Macarrones con chorizo", "descripcion": "Macarrones de toda la vida con chorizo, tomate y queso gratinado.", "instrucciones": "Cuece la pasta y escurre\nSofríe la cebolla y el ajo, añade el chorizo en rodajas y dora\nIncorpora el tomate frito y el orégano y cocina 5 minutos\nMezcla con la pasta y cubre con queso rallado\nGratina o tapa hasta que el queso se funda", "raciones": 4, "prep_min": 10, "cocina_min": 25, "tags": ["batch", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 350, "u": "g"}, {"n": "chorizo", "q": 200, "u": "g"}, {"n": "tomate frito", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}] } $json$::jsonb);

-- 41
select seed_recipe($json$ {"nombre": "Lasaña de verduras", "descripcion": "Lasaña de calabacín y berenjena con bechamel casera y queso.", "instrucciones": "Sofríe la cebolla con el calabacín y la berenjena en dados\nAñade el tomate triturado y cocina 10 minutos\nHaz una bechamel con mantequilla, harina y leche\nMonta capas de pasta, verduras y bechamel en una fuente\nCubre con queso rallado y hornea 25 minutos a 180 grados", "raciones": 4, "prep_min": 30, "cocina_min": 40, "tags": ["horno", "batch", "veggie"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "verdura", "ingredientes": [{"n": "pasta", "q": 250, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "berenjena", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "leche", "q": 500, "u": "ml"}, {"n": "harina de trigo", "q": 40, "u": "g"}, {"n": "mantequilla", "q": 40, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 42
select seed_recipe($json$ {"nombre": "Espaguetis a la carbonara con bacon", "descripcion": "Carbonara cremosa de huevo y queso con bacon dorado.", "instrucciones": "Cuece la pasta y reserva un vaso del agua de cocción\nDora el bacon en tiras con el ajo en una sartén\nBate los huevos con el queso rallado y pimienta\nMezcla la pasta caliente con el bacon fuera del fuego\nAñade la mezcla de huevo y un poco de agua de cocción removiendo hasta que quede cremoso", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "bacon", "q": 80, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}] } $json$::jsonb);

-- 43
select seed_recipe($json$ {"nombre": "Pasta con espinacas y requesón", "descripcion": "Pasta cremosa con espinacas salteadas, requesón y nueces.", "instrucciones": "Cuece la pasta y reserva un poco de agua de cocción\nSaltea el ajo laminado con las espinacas en aceite\nAñade el requesón y un chorrito de agua de cocción para hacer la crema\nMezcla con la pasta y sirve con nueces troceadas y queso rallado", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "espinacas", "q": 250, "u": "g"}, {"n": "requesón", "q": 200, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "nueces", "q": 30, "u": "g"}, {"n": "queso rallado", "q": 30, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 44
select seed_recipe($json$ {"nombre": "Ensalada de pasta con pollo y maíz", "descripcion": "Pasta fría con pollo a la plancha, maíz y aliño de mostaza.", "instrucciones": "Cuece la pasta, escurre y enfría\nHaz la pechuga a la plancha y córtala en tiras\nTrocea el tomate y el pepino\nMezcla todo con el maíz y aliña con aceite, vinagre y mostaza\nEnfría en la nevera antes de servir", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["ensalada", "fiambrera", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "pasta", "q": 160, "u": "g"}, {"n": "pechuga de pollo", "q": 250, "u": "g"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 45
select seed_recipe($json$ {"nombre": "Macarrones con queso gratinados", "descripcion": "Mac and cheese al horno con bechamel y doble capa de queso.", "instrucciones": "Cuece la pasta 2 minutos menos de lo indicado\nHaz una bechamel con mantequilla, harina y leche\nAñade la mitad del queso a la bechamel y mezcla con la pasta\nPasa a una fuente, cubre con el resto del queso\nGratina 10 minutos a 200 grados", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["horno", "veggie"], "temporada": "invierno", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "harina de trigo", "q": 30, "u": "g"}, {"n": "mantequilla", "q": 25, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 46
select seed_recipe($json$ {"nombre": "Espaguetis con gambas al ajillo", "descripcion": "Espaguetis salteados con gambas, ajo dorado y toque de pimentón.", "instrucciones": "Cuece la pasta y reserva un vaso de agua de cocción\nDora los ajos laminados en abundante aceite\nAñade las gambas y el pimentón y saltea 2 minutos\nVierte el vino y deja evaporar\nMezcla con la pasta y un poco de agua de cocción", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "gambas", "q": 250, "u": "g"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "vino blanco", "q": 50, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 47
select seed_recipe($json$ {"nombre": "Pasta con salmón y nata", "descripcion": "Pasta en salsa cremosa con tacos de salmón y cebolla pochada.", "instrucciones": "Cuece la pasta y escurre\nPocha la cebolla y el ajo en aceite\nAñade el salmón en tacos y saltea 3 minutos\nVierte la nata, salpimienta y cuece 5 minutos\nMezcla con la pasta y sirve enseguida", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "salmón", "q": 200, "u": "g"}, {"n": "nata para cocinar", "q": 150, "u": "ml"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 48
select seed_recipe($json$ {"nombre": "Boloñesa de soja texturizada con macarrones", "descripcion": "Boloñesa vegetal de soja texturizada con sofrito de verduras.", "instrucciones": "Hidrata la soja en agua caliente 10 minutos y escurre\nSofríe cebolla, ajo y zanahoria picados en aceite\nAñade la soja y dora 3 minutos\nIncorpora el tomate triturado y el orégano y cuece 20 minutos\nCuece la pasta, escurre y mezcla con la salsa", "raciones": 4, "prep_min": 15, "cocina_min": 30, "tags": ["batch", "veggie", "fiambrera", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 350, "u": "g"}, {"n": "soja texturizada", "q": 150, "u": "g"}, {"n": "tomate triturado", "q": 500, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 49
select seed_recipe($json$ {"nombre": "Pasta con tomate fresco y mozzarella", "descripcion": "Pasta rápida con tomate natural, mozzarella fundida y orégano.", "instrucciones": "Cuece la pasta y escurre\nSofríe el ajo en aceite y añade el tomate en dados\nCocina 8 minutos hasta tener una salsa rústica\nMezcla con la pasta, la mozzarella en trozos y las aceitunas\nTermina con orégano por encima", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "tomate", "q": 3, "u": "pieza"}, {"n": "mozzarella", "q": 125, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "aceitunas", "q": 40, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 50
select seed_recipe($json$ {"nombre": "Ensalada de pasta griega con feta", "descripcion": "Pasta fría estilo griego con feta, pepino, tomate y aceitunas.", "instrucciones": "Cuece la pasta, escurre y enfría\nTrocea el pepino, el tomate y la cebolla en dados\nMezcla con la pasta, las aceitunas y el queso feta desmenuzado\nAliña con aceite, vinagre y orégano y enfría antes de servir", "raciones": 2, "prep_min": 15, "cocina_min": 12, "tags": ["ensalada", "fiambrera", "veggie", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "pasta", "q": 160, "u": "g"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceitunas", "q": 60, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 51
select seed_recipe($json$ {"nombre": "Fideos a la cazuela con lomo", "descripcion": "Cazuela catalana de fideos con lomo de cerdo y sofrito.", "instrucciones": "Dora el lomo en dados en el aceite\nSofríe la cebolla y el ajo, añade el tomate triturado y el pimentón\nIncorpora los fideos y rehoga 2 minutos\nVierte el caldo caliente y cuece 10 minutos\nDeja reposar 3 minutos antes de servir", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["guiso", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "fideos", "q": 180, "u": "g"}, {"n": "lomo de cerdo", "q": 250, "u": "g"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de pollo", "q": 700, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 52
select seed_recipe($json$ {"nombre": "Pasta al horno con berenjena y mozzarella", "descripcion": "Pasta gratinada estilo norma con berenjena y mozzarella fundida.", "instrucciones": "Cuece la pasta 2 minutos menos de lo indicado\nSaltea la berenjena en dados con el ajo en aceite\nMezcla la pasta con la berenjena y el tomate triturado\nPasa a una fuente y reparte la mozzarella y el orégano\nHornea 15 minutos a 200 grados hasta gratinar", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "berenjena", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "mozzarella", "q": 125, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 53
select seed_recipe($json$ {"nombre": "Pasta con brócoli y almendras", "descripcion": "Pasta salteada con brócoli al dente, ajo y almendras tostadas.", "instrucciones": "Cuece la pasta y añade el brócoli en ramitos los últimos 4 minutos\nEscurre reservando un poco de agua\nDora el ajo laminado y las almendras en aceite\nSaltea la pasta y el brócoli en la sartén con un poco de agua de cocción\nSirve con queso rallado y pimienta", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "brócoli", "q": 300, "u": "g"}, {"n": "almendras", "q": 40, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 54
select seed_recipe($json$ {"nombre": "Espaguetis con mejillones al tomate", "descripcion": "Espaguetis con mejillones en salsa de tomate con vino blanco.", "instrucciones": "Cuece la pasta y escurre\nSofríe el ajo en aceite y añade el tomate triturado\nVierte el vino y cuece la salsa 10 minutos\nAñade los mejillones limpios, tapa y cocina hasta que se abran\nMezcla con la pasta y espolvorea orégano", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "mejillones", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 300, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "vino blanco", "q": 50, "u": "ml"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 55
select seed_recipe($json$ {"nombre": "Pasta salteada con pavo y verduras", "descripcion": "Pasta de fiambrera con tiras de pavo, calabacín y pimiento al soja.", "instrucciones": "Cuece la pasta y escurre\nSaltea el pavo en tiras a fuego fuerte y reserva\nSaltea el calabacín, el pimiento y el ajo en la misma sartén\nDevuelve el pavo, añade la pasta y la salsa de soja\nSaltea 2 minutos y deja templar antes de guardar", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["fiambrera", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "filete de pavo", "q": 250, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 56
select seed_recipe($json$ {"nombre": "Albóndigas en salsa de tomate", "descripcion": "Albóndigas caseras de carne mixta guisadas en salsa de tomate.", "instrucciones": "Mezcla la carne con el huevo, el pan rallado, el ajo picado y sal\nForma las albóndigas y enharínalas ligeramente\nDóralas en aceite y reserva\nSofríe la cebolla, añade el tomate frito y las albóndigas\nGuisa 15 minutos a fuego suave", "raciones": 4, "prep_min": 25, "cocina_min": 30, "tags": ["batch", "guiso", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "carne picada mixta", "q": 600, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "pan rallado", "q": 60, "u": "g"}, {"n": "harina de trigo", "q": 30, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 400, "u": "g"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 57
select seed_recipe($json$ {"nombre": "Pastel de carne con puré de patatas", "descripcion": "Pastel de carne picada con tomate cubierto de puré gratinado.", "instrucciones": "Sofríe la cebolla y la zanahoria picadas, añade la carne y dora\nIncorpora el tomate frito y cocina 10 minutos\nCuece las patatas y haz un puré con la leche y la mantequilla\nMonta la carne en una fuente y cubre con el puré\nAñade queso rallado y hornea 20 minutos a 190 grados", "raciones": 4, "prep_min": 25, "cocina_min": 45, "tags": ["horno", "batch"], "temporada": "invierno", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "carne picada de ternera", "q": 500, "u": "g"}, {"n": "patata", "q": 5, "u": "pieza"}, {"n": "leche", "q": 150, "u": "ml"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 58
select seed_recipe($json$ {"nombre": "Berenjenas rellenas de carne picada", "descripcion": "Berenjenas asadas rellenas de carne con tomate y queso gratinado.", "instrucciones": "Asa las berenjenas a la mitad 25 minutos a 200 grados y vacíalas\nSofríe la cebolla, añade la carne y dórala\nIncorpora la pulpa de berenjena picada, el tomate frito y el orégano\nRellena las berenjenas y cubre con queso rallado\nGratina 10 minutos hasta dorar", "raciones": 4, "prep_min": 20, "cocina_min": 45, "tags": ["horno", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "berenjena", "q": 4, "u": "pieza"}, {"n": "carne picada mixta", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 59
select seed_recipe($json$ {"nombre": "Calabacines rellenos de atún", "descripcion": "Calabacines al horno rellenos de atún con tomate y queso.", "instrucciones": "Corta los calabacines a lo largo, vacíalos y pica la pulpa\nSofríe la cebolla con la pulpa de calabacín\nAñade el atún, el tomate frito y el huevo batido\nRellena los calabacines, cubre con pan rallado y queso\nHornea 25 minutos a 190 grados", "raciones": 2, "prep_min": 20, "cocina_min": 35, "tags": ["horno"], "temporada": "verano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "calabacín", "q": 2, "u": "pieza"}, {"n": "atún en lata", "q": 160, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 150, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "pan rallado", "q": 30, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}] } $json$::jsonb);

-- 60
select seed_recipe($json$ {"nombre": "Pimientos rellenos de arroz y champiñones", "descripcion": "Pimientos asados rellenos de arroz con champiñones y queso.", "instrucciones": "Cuece el arroz 15 minutos y escurre\nSofríe la cebolla con los champiñones picados\nMezcla con el arroz, el tomate triturado y el orégano\nRellena los pimientos sin tapa y cubre con queso rallado\nHornea 30 minutos a 190 grados", "raciones": 2, "prep_min": 20, "cocina_min": 45, "tags": ["horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "pimiento rojo", "q": 4, "u": "pieza"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "champiñones", "q": 100, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 61
select seed_recipe($json$ {"nombre": "Coliflor gratinada con jamón y bechamel", "descripcion": "Coliflor al horno con bechamel, jamón cocido y queso fundido.", "instrucciones": "Cuece la coliflor en ramitos y las patatas en rodajas 12 minutos\nHaz una bechamel con mantequilla, harina y leche\nColoca la verdura en una fuente con el jamón en tiras\nCubre con la bechamel y el queso rallado\nGratina 15 minutos a 200 grados", "raciones": 4, "prep_min": 15, "cocina_min": 35, "tags": ["horno", "batch"], "temporada": "invierno", "batch_days": 2, "principal": "verdura", "ingredientes": [{"n": "coliflor", "q": 800, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "jamón cocido", "q": 150, "u": "g"}, {"n": "leche", "q": 600, "u": "ml"}, {"n": "harina de trigo", "q": 50, "u": "g"}, {"n": "mantequilla", "q": 50, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 62
select seed_recipe($json$ {"nombre": "Pisto manchego con huevo", "descripcion": "Pisto de verduras pochadas con huevos a la plancha y pan.", "instrucciones": "Pocha la cebolla y los pimientos picados en aceite\nAñade el calabacín y la berenjena en dados y cocina 15 minutos\nIncorpora el tomate triturado y guisa 15 minutos más\nHaz los huevos a la plancha y sírvelos sobre el pisto con pan", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["veggie", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "berenjena", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 63
select seed_recipe($json$ {"nombre": "Tortilla de patatas con cebolla", "descripcion": "Tortilla española jugosa de patata y cebolla pochada.", "instrucciones": "Pela y corta las patatas en láminas finas y la cebolla en juliana\nPóchalas en abundante aceite a fuego medio 20 minutos\nEscurre y mezcla con los huevos batidos y sal\nCuaja la tortilla en la sartén 4 minutos por cada lado\nDeja reposar antes de cortar", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "fiambrera", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "patata", "q": 3, "u": "pieza"}, {"n": "huevo", "q": 5, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 64
select seed_recipe($json$ {"nombre": "Tortilla de calabacín y queso", "descripcion": "Tortilla esponjosa de calabacín pochado con queso rallado.", "instrucciones": "Pocha el calabacín en rodajas finas con la cebolla en aceite\nEscurre y mezcla con los huevos batidos, el queso y sal\nCuaja la tortilla a fuego medio 4 minutos por lado\nDeja templar antes de cortar", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["veggie", "fiambrera", "rapida", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "calabacín", "q": 2, "u": "pieza"}, {"n": "huevo", "q": 5, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 65
select seed_recipe($json$ {"nombre": "Pollo asado con patatas al limón", "descripcion": "Muslos de pollo asados con patatas, limón y tomillo.", "instrucciones": "Precalienta el horno a 200 grados\nColoca en una bandeja los muslos, las patatas en gajos y la cebolla\nAliña con aceite, ajo picado, tomillo, sal y el zumo del limón\nVierte el vino y hornea 50 minutos dando la vuelta a mitad\nSirve regado con el jugo de la bandeja", "raciones": 4, "prep_min": 15, "cocina_min": 55, "tags": ["horno", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 1000, "u": "g"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 66
select seed_recipe($json$ {"nombre": "Pollo al ajillo con arroz blanco", "descripcion": "Pollo troceado al ajillo con vino blanco y arroz de guarnición.", "instrucciones": "Dora el pollo troceado y salado en aceite a fuego vivo\nAñade los ajos laminados y el tomillo y dóralos\nVierte el vino y guisa 15 minutos a fuego medio\nCuece el arroz aparte 15 minutos y escurre\nSirve el pollo con su salsa sobre el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 500, "u": "g"}, {"n": "ajo", "q": 6, "u": "pieza"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 67
select seed_recipe($json$ {"nombre": "Chili con carne exprés con arroz", "descripcion": "Chili rápido de carne picada y alubias servido con arroz blanco.", "instrucciones": "Sofríe la cebolla y el ajo en aceite\nAñade la carne picada y dórala desmenuzándola\nIncorpora el comino, el pimentón, el tomate triturado y las alubias\nGuisa 20 minutos a fuego suave\nCuece el arroz aparte y sirve el chili encima", "raciones": 4, "prep_min": 10, "cocina_min": 35, "tags": ["batch", "fiambrera", "guiso", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "carne picada mixta", "q": 400, "u": "g"}, {"n": "alubias blancas cocidas", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "arroz", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "comino", "q": 2, "u": "cdta"}, {"n": "pimentón", "q": 2, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 68
select seed_recipe($json$ {"nombre": "Lomo de cerdo en salsa de champiñones", "descripcion": "Medallones de lomo en salsa cremosa de champiñones con patatas.", "instrucciones": "Dora los medallones de lomo salpimentados y reserva\nPocha la cebolla y el ajo y añade los champiñones\nVierte el vino y deja reducir\nIncorpora la nata y el lomo y cuece 10 minutos a fuego suave\nSirve con las patatas cocidas o asadas", "raciones": 4, "prep_min": 15, "cocina_min": 35, "tags": ["batch", "sin-horno"], "temporada": "invierno", "batch_days": 2, "principal": "cerdo", "ingredientes": [{"n": "lomo de cerdo", "q": 600, "u": "g"}, {"n": "champiñones", "q": 300, "u": "g"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 69
select seed_recipe($json$ {"nombre": "Pavo en salsa de mostaza y miel con arroz", "descripcion": "Filetes de pavo en salsa cremosa de mostaza y miel con arroz.", "instrucciones": "Cuece el arroz 15 minutos y escurre\nDora los filetes de pavo en aceite y reserva\nPocha la cebolla, añade la mostaza, la miel y la nata\nDevuelve el pavo y cocina 5 minutos en la salsa\nSirve sobre el arroz blanco", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "filete de pavo", "q": 300, "u": "g"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "nata para cocinar", "q": 150, "u": "ml"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 2, "u": "cdta"}, {"n": "miel", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 70
select seed_recipe($json$ {"nombre": "Salmón al horno con boniato y brócoli", "descripcion": "Lomos de salmón al horno con boniato asado y brócoli.", "instrucciones": "Precalienta el horno a 200 grados\nAsa el boniato en dados con aceite, sal y tomillo 20 minutos\nAñade el brócoli en ramitos y el salmón con ajo y limón\nHornea 12 minutos más hasta que el salmón esté en su punto", "raciones": 2, "prep_min": 10, "cocina_min": 35, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 300, "u": "g"}, {"n": "boniato", "q": 2, "u": "pieza"}, {"n": "brócoli", "q": 200, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 71
select seed_recipe($json$ {"nombre": "Merluza en salsa verde con guisantes", "descripcion": "Lomos de merluza en salsa verde de ajo y vino con guisantes y patata.", "instrucciones": "Cuece las patatas en rodajas 15 minutos y reserva\nDora el ajo picado en aceite y añade la harina\nVierte el vino y un vaso de agua removiendo hasta ligar la salsa\nIncorpora la merluza y los guisantes y cuece 8 minutos moviendo la cazuela\nSirve sobre las patatas", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 400, "u": "g"}, {"n": "guisantes", "q": 150, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "harina de trigo", "q": 20, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 72
select seed_recipe($json$ {"nombre": "Dorada al horno con patatas panadera", "descripcion": "Dorada entera al horno sobre cama de patatas y cebolla.", "instrucciones": "Precalienta el horno a 200 grados\nHaz una cama con las patatas y la cebolla en rodajas finas con aceite y sal\nHornea la cama 25 minutos\nColoca la dorada encima con limón y tomillo y riega con el vino\nHornea 20 minutos más hasta que el pescado esté hecho", "raciones": 2, "prep_min": 15, "cocina_min": 50, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "dorada", "q": 600, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 73
select seed_recipe($json$ {"nombre": "Boquerones fritos con ensalada de tomate", "descripcion": "Boquerones enharinados y fritos con ensalada fresca de tomate.", "instrucciones": "Limpia los boquerones, sálalos y pásalos por harina\nFríelos en aceite caliente por tandas hasta dorar\nEscurre sobre papel absorbente\nPrepara una ensalada con lechuga, tomate y cebolla\nAliña con aceite y vinagre y sirve con limón", "raciones": 2, "prep_min": 20, "cocina_min": 15, "tags": ["sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "boquerones", "q": 400, "u": "g"}, {"n": "harina de trigo", "q": 60, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 74
select seed_recipe($json$ {"nombre": "Bol de quinoa con pollo y aguacate", "descripcion": "Bol templado de quinoa con pollo a la plancha, verduras y aguacate.", "instrucciones": "Cuece la quinoa 15 minutos y escurre\nHaz la pechuga a la plancha y córtala en tiras\nSaltea el calabacín y la zanahoria en daditos\nMonta el bol con la quinoa, el pollo, las verduras y el aguacate\nAliña con aceite, zumo de limón y sal", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["fiambrera", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "quinoa", "q": 160, "u": "g"}, {"n": "pechuga de pollo", "q": 250, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 75
select seed_recipe($json$ {"nombre": "Ensalada de quinoa con aguacate y feta", "descripcion": "Ensalada fría de quinoa con aguacate, pepino, tomate y feta.", "instrucciones": "Cuece la quinoa 15 minutos, escurre y enfría\nTrocea el pepino, el tomate y el aguacate\nMezcla todo con el queso feta desmenuzado\nAliña con aceite, zumo de limón y sal", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["ensalada", "fiambrera", "veggie", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "quinoa", "q": 150, "u": "g"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 80, "u": "g"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 76
select seed_recipe($json$ {"nombre": "Cuscús con verduras y garbanzos", "descripcion": "Cuscús especiado con verduras salteadas y garbanzos.", "instrucciones": "Hidrata el cuscús con el caldo hirviendo 5 minutos y suelta con un tenedor\nSaltea la cebolla, la zanahoria y el calabacín en dados\nAñade los garbanzos y el comino y saltea 5 minutos\nMezcla con el cuscús, rectifica de sal y sirve", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["fiambrera", "veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "cuscús", "q": 160, "u": "g"}, {"n": "garbanzos cocidos", "q": 300, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 250, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 77
select seed_recipe($json$ {"nombre": "Cuscús con pollo especiado", "descripcion": "Cuscús al estilo marroquí con pollo al comino, pimentón y canela.", "instrucciones": "Hidrata el cuscús con agua hirviendo y un poco de aceite\nSaltea la pechuga en tacos con comino, pimentón y una pizca de canela\nAñade la cebolla y el pimiento rojo en tiras y sofríe\nMezcla con el cuscús y termina con zumo de limón", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["fiambrera", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "cuscús", "q": 160, "u": "g"}, {"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "canela", "q": 1, "u": "cdta"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 78
select seed_recipe($json$ {"nombre": "Wraps de pollo con aguacate", "descripcion": "Tortillas de trigo rellenas de pollo, aguacate y salsa de yogur.", "instrucciones": "Haz la pechuga a la plancha y córtala en tiras\nMezcla el yogur con sal y un poco de aceite para la salsa\nReparte en las tortillas la lechuga, el tomate, el pollo y el aguacate\nSalsea, enrolla bien apretado y corta por la mitad", "raciones": 2, "prep_min": 15, "cocina_min": 10, "tags": ["fiambrera", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "yogur natural", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 79
select seed_recipe($json$ {"nombre": "Burritos de soja texturizada", "descripcion": "Burritos vegetales con soja texturizada al comino, maíz y queso.", "instrucciones": "Hidrata la soja en agua caliente 10 minutos y escurre\nSofríe la cebolla, añade la soja y el comino y dora\nIncorpora el tomate frito y el maíz y cocina 5 minutos\nRellena las tortillas con la mezcla y el queso rallado\nEnrolla y marca en la sartén 1 minuto por lado", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["fiambrera", "veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "soja texturizada", "q": 100, "u": "g"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "maíz dulce", "q": 80, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}] } $json$::jsonb);

-- 80
select seed_recipe($json$ {"nombre": "Tofu salteado con verduras y arroz", "descripcion": "Salteado oriental de tofu con brócoli, zanahoria, soja y sésamo.", "instrucciones": "Cuece el arroz 15 minutos y escurre\nDora el tofu en dados en aceite y reserva\nSaltea el brócoli, la zanahoria y el ajo a fuego fuerte\nDevuelve el tofu, añade la salsa de soja y el sésamo\nSirve sobre el arroz", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["fiambrera", "veggie", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "tofu", "q": 300, "u": "g"}, {"n": "arroz", "q": 160, "u": "g"}, {"n": "brócoli", "q": 200, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 3, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}] } $json$::jsonb);

-- 81
select seed_recipe($json$ {"nombre": "Salteado de garbanzos con espinacas y huevo", "descripcion": "Garbanzos salteados al pimentón con espinacas y huevo a la plancha.", "instrucciones": "Dora el ajo laminado en aceite\nAñade los garbanzos con el pimentón y el comino y saltea 5 minutos\nIncorpora las espinacas hasta que mengüen\nHaz los huevos a la plancha y sírvelos encima con pan", "raciones": 2, "prep_min": 5, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "espinacas", "q": 250, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 82
select seed_recipe($json$ {"nombre": "Ensalada de lentejas con verduras frescas", "descripcion": "Lentejas frías con tomate, pimiento, pepino y queso feta.", "instrucciones": "Cuece las lentejas 25 minutos, escurre y enfría\nPica el tomate, el pimiento, la cebolla y el pepino en daditos\nMezcla con las lentejas y el feta desmenuzado\nAliña con aceite, vinagre y sal y enfría en la nevera", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["ensalada", "fiambrera", "veggie", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 180, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 60, "u": "g"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 83
select seed_recipe($json$ {"nombre": "Ensalada de garbanzos con atún", "descripcion": "Garbanzos fríos con atún, tomate, pepino y aceitunas.", "instrucciones": "Enjuaga y escurre los garbanzos\nPica el tomate, la cebolla y el pepino\nMezcla todo con el atún escurrido y las aceitunas\nAliña con aceite, vinagre y sal y deja reposar 10 minutos en frío", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["ensalada", "fiambrera", "rapida", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "aceitunas", "q": 40, "u": "g"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 84
select seed_recipe($json$ {"nombre": "Hamburguesas caseras con ensalada", "descripcion": "Hamburguesas de ternera en pan con ensalada de lechuga y tomate.", "instrucciones": "Mezcla la carne con el huevo, el pan rallado, sal y pimienta\nForma dos hamburguesas y hazlas a la plancha 4 minutos por lado\nTuesta el pan y úntalo con mostaza\nMonta con lechuga, tomate y cebolla en aros\nSirve con el resto de la ensalada aliñada", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "carne picada de ternera", "q": 300, "u": "g"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "pan rallado", "q": 30, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}] } $json$::jsonb);

-- 85
select seed_recipe($json$ {"nombre": "Salchichas con pisto de verduras", "descripcion": "Salchichas frescas doradas sobre pisto rápido de calabacín y pimiento.", "instrucciones": "Pocha la cebolla y el pimiento rojo picados en aceite\nAñade el calabacín en dados y cocina 10 minutos\nIncorpora el tomate triturado y el orégano y guisa 10 minutos más\nDora las salchichas en una sartén aparte\nSirve las salchichas sobre el pisto", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "salchichas frescas", "q": 250, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 300, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}] } $json$::jsonb);

select validate_seed_recipes();
