-- Lote 3: pescados, veggie, temporada y fin de semana (85 recetas)

-- ============================================================
-- Pescados y mariscos (25)
-- ============================================================

select seed_recipe($json$ {"nombre": "Merluza en salsa verde", "descripcion": "Lomos de merluza en suave salsa de ajo, vino blanco y guisantes con patata cocida.", "instrucciones": "Cuece las patatas en rodajas 15 minutos\nSofríe el ajo picado en aceite y añade la harina\nMoja con vino blanco y caldo y deja reducir\nIncorpora la merluza y los guisantes y cocina 8 minutos\nSirve la merluza con la salsa y las patatas", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 400, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "guisantes", "q": 100, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 200, "u": "ml"}, {"n": "harina de trigo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Dorada al horno con patatas panadera", "descripcion": "Dorada entera asada sobre cama de patata y cebolla regada con vino blanco.", "instrucciones": "Corta patata y cebolla en rodajas finas y hornéalas 20 minutos con aceite\nColoca la dorada salpimentada encima con rodajas de limón\nRiega con el vino blanco\nHornea 20 minutos más a 190 grados", "raciones": 2, "prep_min": 15, "cocina_min": 40, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "dorada", "q": 600, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Mejillones al vapor con limón", "descripcion": "Mejillones abiertos al vapor con ajo, laurel y un toque de vino blanco.", "instrucciones": "Limpia bien los mejillones retirando las barbas\nSofríe el ajo en aceite en una olla amplia\nAñade los mejillones, el vino y el laurel y tapa\nCocina 5 minutos hasta que se abran\nSirve con limón y pan para mojar", "raciones": 2, "prep_min": 15, "cocina_min": 10, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "mejillones", "q": 1000, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "pan", "q": 2, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Calamares encebollados con arroz", "descripcion": "Anillas de calamar guisadas con mucha cebolla pochada y pimentón.", "instrucciones": "Pocha la cebolla en juliana a fuego lento 15 minutos\nAñade el ajo y el pimentón\nIncorpora los calamares y el vino blanco\nGuisa 20 minutos hasta que estén tiernos\nSirve con arroz blanco cocido", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["sin-horno", "guiso"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "calamares", "q": 500, "u": "g"}, {"n": "cebolla", "q": 3, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "arroz", "q": 140, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salmón a la plancha con brócoli", "descripcion": "Lomos de salmón dorados con brócoli al vapor y aliño de limón y ajo.", "instrucciones": "Cuece el brócoli al vapor 6 minutos\nMarca el salmón salpimentado en plancha caliente 3 minutos por lado\nDora el ajo laminado en aceite\nRiega salmón y brócoli con el ajo y zumo de limón", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 400, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bacalao al pil-pil con patatas", "descripcion": "Bacalao confitado en aceite de ajo con su salsa ligada y patata cocida.", "instrucciones": "Cuece las patatas en rodajas y reserva\nDora los ajos laminados en abundante aceite y retíralos\nConfita el bacalao a fuego suave 8 minutos\nLiga la salsa moviendo la cazuela en círculos\nSirve con los ajos, el pimentón y las patatas", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "bacalao", "q": 400, "u": "g"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 6, "u": "cda"}, {"n": "pimentón", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Gambas al ajillo con arroz blanco", "descripcion": "Gambas salteadas en aceite de ajo y pimentón servidas sobre arroz.", "instrucciones": "Cuece el arroz en agua con sal y escurre\nDora el ajo laminado en aceite caliente\nAñade las gambas y saltea 3 minutos\nEspolvorea pimentón fuera del fuego\nSirve las gambas con su aceite sobre el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "gambas", "q": 300, "u": "g"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Boquerones fritos con ensalada verde", "descripcion": "Boquerones enharinados y fritos acompañados de ensalada fresca con limón.", "instrucciones": "Limpia los boquerones y sécalos bien\nEnharínalos y fríelos en aceite caliente por tandas\nEscúrrelos sobre papel absorbente\nPrepara una ensalada de lechuga y tomate\nSirve con gajos de limón", "raciones": 2, "prep_min": 20, "cocina_min": 15, "tags": ["sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "boquerones", "q": 400, "u": "g"}, {"n": "harina de trigo", "q": 60, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Marmitako exprés de atún", "descripcion": "Guiso marinero de patata, pimiento y tomate rematado con atún en conserva.", "instrucciones": "Sofríe cebolla, pimiento y ajo picados\nAñade pimentón y el tomate triturado y cocina 5 minutos\nIncorpora las patatas chascadas, el laurel y el caldo\nGuisa 25 minutos hasta que la patata esté tierna\nAparta del fuego y añade el atún escurrido", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["guiso", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "atún en lata", "q": 160, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "caldo de verduras", "q": 400, "u": "ml"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salmón al horno con tomillo y limón", "descripcion": "Lomos de salmón horneados con calabacín, tomillo y rodajas de limón.", "instrucciones": "Precalienta el horno a 200 grados\nCorta el calabacín en medias lunas y extiéndelo en la bandeja\nColoca el salmón encima con limón, tomillo, sal y aceite\nHornea 18 minutos", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["horno", "rapida"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 400, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Merluza a la romana con puré de patata", "descripcion": "Filetes de merluza rebozados y fritos con puré casero de patata.", "instrucciones": "Cuece las patatas y haz un puré con leche y mantequilla\nSalpimienta la merluza y pásala por harina y huevo\nFríela en aceite caliente 3 minutos por lado\nEscurre sobre papel y sirve con el puré", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 400, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "harina de trigo", "q": 60, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "leche", "q": 100, "u": "ml"}, {"n": "mantequilla", "q": 20, "u": "g"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bacalao con tomate", "descripcion": "Tacos de bacalao en salsa de tomate casera ligeramente dulce.", "instrucciones": "Sofríe cebolla y ajo picados 8 minutos\nAñade el tomate triturado y el azúcar y cocina 15 minutos\nIncorpora el bacalao en tacos\nCocina 8 minutos a fuego suave\nSirve con pan", "raciones": 2, "prep_min": 10, "cocina_min": 30, "tags": ["sin-horno", "guiso"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "bacalao", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "azúcar", "q": 5, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "pan", "q": 1, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Arroz caldoso de mejillones", "descripcion": "Arroz meloso con mejillones, sofrito de tomate y un punto de pimentón.", "instrucciones": "Abre los mejillones al vapor y reserva su jugo colado\nSofríe cebolla y ajo, añade tomate y pimentón\nIncorpora el arroz y rehoga 2 minutos\nVierte el caldo y el jugo de los mejillones y cuece 16 minutos\nAñade los mejillones al final y sirve caldoso", "raciones": 2, "prep_min": 20, "cocina_min": 30, "tags": ["guiso", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "mejillones", "q": 800, "u": "g"}, {"n": "arroz", "q": 180, "u": "g"}, {"n": "tomate triturado", "q": 150, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 700, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Fideuá de gambas y calamares", "descripcion": "Fideos dorados en sartén con gambas, calamares y caldo con pimentón.", "instrucciones": "Dora los fideos en aceite y reserva\nSofríe ajo, calamares y tomate triturado\nAñade pimentón, los fideos y el caldo caliente\nCuece 8 minutos y coloca las gambas encima\nDeja reposar 3 minutos antes de servir", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "fideos", "q": 200, "u": "g"}, {"n": "gambas", "q": 200, "u": "g"}, {"n": "calamares", "q": 200, "u": "g"}, {"n": "tomate triturado", "q": 100, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Dorada a la plancha con verduras salteadas", "descripcion": "Filetes de dorada a la plancha con salteado rápido de calabacín y pimiento.", "instrucciones": "Saltea cebolla, pimiento y calabacín en tiras 8 minutos\nMarca los filetes de dorada con la piel hacia abajo 4 minutos\nDales la vuelta y cocina 2 minutos más\nSirve con las verduras y un chorrito de limón", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "dorada", "q": 600, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salpicón de marisco", "descripcion": "Gambas y mejillones fríos con pimientos, cebolla, huevo y vinagreta.", "instrucciones": "Cuece las gambas y abre los mejillones al vapor\nCuece los huevos 10 minutos y pícalos\nPica los pimientos y la cebolla muy finos\nMezcla todo con aceite, vinagre y sal\nEnfría en nevera al menos 30 minutos", "raciones": 2, "prep_min": 25, "cocina_min": 15, "tags": ["ensalada", "sin-horno", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "gambas", "q": 200, "u": "g"}, {"n": "mejillones", "q": 300, "u": "g"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "vinagre", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Curry de gambas con leche de coco", "descripcion": "Gambas en salsa cremosa de curry y coco servidas con arroz basmati.", "instrucciones": "Cuece el arroz y reserva\nSofríe la cebolla picada y añade el curry\nIncorpora el tomate triturado y la leche de coco y reduce 8 minutos\nAñade las gambas y cocina 4 minutos\nSirve sobre el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "gambas", "q": 300, "u": "g"}, {"n": "leche de coco", "q": 200, "u": "ml"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 150, "u": "g"}, {"n": "arroz", "q": 150, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tacos de salmón con aguacate", "descripcion": "Tortillas de trigo con salmón especiado, aguacate y ensalada fresca.", "instrucciones": "Adoba el salmón en dados con comino y sal\nSaltéalo 4 minutos en sartén caliente\nCalienta las tortillas\nRellena con lechuga, tomate, salmón y aguacate\nTermina con zumo de limón", "raciones": 2, "prep_min": 15, "cocina_min": 10, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 300, "u": "g"}, {"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bacalao a la vizcaína casera", "descripcion": "Bacalao en salsa roja de pimiento, tomate y cebolla ligada con pan.", "instrucciones": "Pocha la cebolla, el ajo y el pimiento rojo 15 minutos\nAñade el tomate triturado y el pan troceado y cocina 10 minutos\nTritura la salsa hasta que quede fina\nIncorpora el bacalao y cocina 8 minutos a fuego suave", "raciones": 2, "prep_min": 15, "cocina_min": 40, "tags": ["guiso", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "bacalao", "q": 400, "u": "g"}, {"n": "pimiento rojo", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "cebolla", "q": 2, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Papillote de merluza con verduras", "descripcion": "Merluza al horno en paquete de papel con zanahoria, puerro y calabacín.", "instrucciones": "Corta las verduras en juliana fina\nColoca cada lomo de merluza sobre papel de horno con las verduras\nRiega con vino blanco y aceite y cierra los paquetes\nHornea 15 minutos a 200 grados\nAbre el papillote en la mesa", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["horno", "rapida"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 400, "u": "g"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 50, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Calamares guisados con guisantes y patata", "descripcion": "Guiso de calamar tierno con patata, guisantes y sofrito de tomate.", "instrucciones": "Sofríe la cebolla picada y añade el tomate triturado\nIncorpora los calamares en anillas y el vino blanco\nAñade las patatas chascadas, el laurel y agua hasta cubrir\nGuisa 30 minutos\nAñade los guisantes y cocina 5 minutos más", "raciones": 2, "prep_min": 15, "cocina_min": 45, "tags": ["guiso", "sin-horno", "fiambrera"], "temporada": "invierno", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "calamares", "q": 500, "u": "g"}, {"n": "guisantes", "q": 150, "u": "g"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Espaguetis con atún y aceitunas", "descripcion": "Pasta rápida con sofrito de tomate, atún en conserva y aceitunas.", "instrucciones": "Cuece la pasta al dente y escurre\nDora el ajo laminado en aceite\nAñade el tomate frito, el atún y las aceitunas\nMezcla con la pasta y espolvorea orégano", "raciones": 2, "prep_min": 5, "cocina_min": 15, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "pasta", "q": 200, "u": "g"}, {"n": "atún en lata", "q": 160, "u": "g"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "aceitunas", "q": 50, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Albóndigas de merluza en salsa verde", "descripcion": "Albóndigas caseras de merluza guisadas con guisantes en salsa de vino blanco.", "instrucciones": "Pica la merluza y mézclala con pan rallado, huevo y ajo\nForma albóndigas y enharínalas ligeramente\nDóralas en aceite y retira\nHaz la salsa con vino, caldo y guisantes\nGuisa las albóndigas en la salsa 10 minutos", "raciones": 2, "prep_min": 25, "cocina_min": 25, "tags": ["sin-horno", "guiso"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "merluza", "q": 400, "u": "g"}, {"n": "pan rallado", "q": 50, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "harina de trigo", "q": 20, "u": "g"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 200, "u": "ml"}, {"n": "guisantes", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salmón con quinoa y espinacas", "descripcion": "Lomo de salmón a la sartén sobre quinoa con espinacas salteadas y sésamo.", "instrucciones": "Cuece la quinoa 15 minutos y escurre\nSaltea las espinacas con un poco de aceite\nMarca el salmón 3 minutos por cada lado\nMonta el plato con quinoa, espinacas y salmón\nTermina con sésamo y zumo de limón", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "salmon", "ingredientes": [{"n": "salmón", "q": 400, "u": "g"}, {"n": "quinoa", "q": 140, "u": "g"}, {"n": "espinacas", "q": 150, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Wok de gambas y fideos con verduras", "descripcion": "Fideos salteados al wok con gambas, brócoli, zanahoria y salsa de soja.", "instrucciones": "Cuece los fideos según el paquete y escurre\nSaltea el ajo, la zanahoria y el brócoli en aceite bien caliente\nAñade las gambas y saltea 3 minutos\nIncorpora los fideos y la salsa de soja\nTermina con sésamo por encima", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "marisco", "ingredientes": [{"n": "gambas", "q": 250, "u": "g"}, {"n": "fideos", "q": 160, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

-- ============================================================
-- Platos vegetarianos, tofu y legumbre moderna (25)
-- ============================================================

select seed_recipe($json$ {"nombre": "Curry de garbanzos con leche de coco", "descripcion": "Garbanzos guisados en salsa cremosa de curry, tomate y coco con arroz.", "instrucciones": "Cuece el arroz y reserva\nSofríe la cebolla y el ajo picados\nAñade curry y comino y tuesta 1 minuto\nIncorpora tomate triturado, leche de coco y garbanzos\nCocina 15 minutos y sirve con el arroz", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["veggie", "sin-horno", "guiso", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "leche de coco", "q": 200, "u": "ml"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tofu salteado con brócoli y sésamo", "descripcion": "Dados de tofu dorados con brócoli, soja y sésamo sobre arroz.", "instrucciones": "Cuece el arroz y reserva\nDora el tofu en dados en aceite caliente\nAñade el brócoli en ramilletes y el ajo y saltea 6 minutos\nIncorpora la salsa de soja\nSirve sobre el arroz con sésamo", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "tofu", "q": 300, "u": "g"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 3, "u": "cda"}, {"n": "sésamo", "q": 15, "u": "g"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Boloñesa de soja texturizada con pasta", "descripcion": "Salsa boloñesa vegetal de soja texturizada con sofrito de verduras.", "instrucciones": "Hidrata la soja texturizada en agua caliente 10 minutos\nSofríe cebolla, zanahoria y ajo picados\nAñade la soja escurrida y el tomate triturado\nCocina 20 minutos con orégano\nSirve sobre la pasta cocida", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "soja texturizada", "q": 80, "u": "g"}, {"n": "pasta", "q": 200, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Hamburguesas de lentejas con ensalada", "descripcion": "Hamburguesas vegetales de lenteja y avena con ensalada de lechuga y tomate.", "instrucciones": "Cuece las lentejas hasta que estén tiernas y escurre bien\nTritúralas con cebolla, comino, huevo y avena\nForma hamburguesas y pásalas por pan rallado\nDóralas 4 minutos por lado en sartén con aceite\nSirve con ensalada aliñada", "raciones": 2, "prep_min": 25, "cocina_min": 35, "tags": ["veggie", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 160, "u": "g"}, {"n": "avena", "q": 40, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "pan rallado", "q": 40, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bowl de quinoa, garbanzos y aguacate", "descripcion": "Bol templado de quinoa con garbanzos especiados, aguacate y pepino.", "instrucciones": "Cuece la quinoa 15 minutos y escurre\nSaltea los garbanzos con comino y aceite 5 minutos\nCorta tomate, pepino y aguacate en dados\nMonta el bol y aliña con limón, aceite y sal", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["veggie", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "quinoa", "q": 140, "u": "g"}, {"n": "garbanzos cocidos", "q": 200, "u": "g"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tacos de soja texturizada", "descripcion": "Tortillas rellenas de soja texturizada especiada con aguacate y lechuga.", "instrucciones": "Hidrata la soja en agua caliente y escurre\nSaltéala con cebolla, pimentón y comino 8 minutos\nAñade el tomate picado\nCalienta las tortillas y rellena con la soja, lechuga y aguacate", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "soja texturizada", "q": 80, "u": "g"}, {"n": "tortillas de trigo", "q": 4, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "aguacate", "q": 1, "u": "pieza"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Chili vegetariano de alubias y maíz", "descripcion": "Guiso especiado de alubias blancas, maíz y pimiento servido con arroz.", "instrucciones": "Sofríe cebolla, ajo y pimiento rojo picados\nAñade comino y pimentón y tuesta 1 minuto\nIncorpora tomate triturado, alubias y maíz\nGuisa 20 minutos a fuego medio\nSirve con arroz blanco", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "guiso", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "alubias blancas cocidas", "q": 400, "u": "g"}, {"n": "maíz dulce", "q": 140, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tofu al curry con calabaza", "descripcion": "Tofu y calabaza en salsa de curry con leche de coco y arroz.", "instrucciones": "Cuece el arroz y reserva\nDora el tofu en dados y retira\nSofríe la cebolla y añade el curry y la calabaza en dados\nVierte la leche de coco y cocina 15 minutos\nDevuelve el tofu, calienta y sirve con arroz", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["veggie", "sin-horno", "guiso"], "temporada": "otono", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "tofu", "q": 300, "u": "g"}, {"n": "calabaza", "q": 300, "u": "g"}, {"n": "leche de coco", "q": 200, "u": "ml"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Hummus casero con crudités y pan", "descripcion": "Crema de garbanzos con sésamo y comino para mojar verduras y pan.", "instrucciones": "Tritura los garbanzos con ajo, limón, sésamo, comino y aceite\nAjusta de sal y textura con un poco de agua fría\nCorta zanahoria y pepino en bastones\nSirve el hummus con las crudités y el pan tostado", "raciones": 2, "prep_min": 15, "cocina_min": 5, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "sésamo", "q": 20, "u": "g"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Lentejas estofadas de verduras", "descripcion": "Lentejas guisadas a fuego lento con puerro, zanahoria y pimentón.", "instrucciones": "Sofríe el puerro y la zanahoria picados\nAñade el pimentón y remueve\nIncorpora las lentejas, la patata, el tomate, el laurel y el caldo\nGuisa 35 minutos a fuego suave\nRectifica de sal antes de servir", "raciones": 2, "prep_min": 15, "cocina_min": 45, "tags": ["veggie", "guiso", "sin-horno", "fiambrera"], "temporada": "invierno", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 200, "u": "g"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "laurel", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 800, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Garbanzos crujientes al horno con ensalada feta", "descripcion": "Garbanzos especiados tostados al horno sobre ensalada con queso feta.", "instrucciones": "Seca los garbanzos y mézclalos con aceite, pimentón y comino\nHornéalos 25 minutos a 200 grados removiendo a mitad\nPrepara una ensalada de lechuga, tomate y pepino\nAñade el feta desmigado y los garbanzos calientes\nAliña con aceite y sal", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "horno", "ensalada"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Fideos salteados con tofu y cacahuetes", "descripcion": "Fideos al wok con tofu, pimiento y zanahoria con soja y cacahuete.", "instrucciones": "Cuece los fideos y escurre\nDora el tofu en dados y reserva\nSaltea ajo, zanahoria y pimiento en tiras\nAñade fideos, tofu y salsa de soja y saltea 2 minutos\nSirve con cacahuetes picados", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "fideos", "q": 160, "u": "g"}, {"n": "tofu", "q": 200, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 3, "u": "cda"}, {"n": "cacahuetes", "q": 30, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Coliflor asada con especias y yogur", "descripcion": "Coliflor al horno con pimentón, comino y curry, garbanzos y salsa de yogur.", "instrucciones": "Corta la coliflor en ramilletes y mézclala con aceite y especias\nHornea 30 minutos a 210 grados con los garbanzos\nMezcla el yogur con zumo de limón y sal\nSirve la coliflor con la salsa por encima", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["veggie", "horno"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "coliflor", "q": 1, "u": "pieza"}, {"n": "garbanzos cocidos", "q": 200, "u": "g"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "curry", "q": 1, "u": "cdta"}, {"n": "yogur natural", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Berenjenas rellenas de soja texturizada", "descripcion": "Berenjenas asadas rellenas de boloñesa vegetal y gratinadas con queso.", "instrucciones": "Asa las berenjenas partidas por la mitad 25 minutos\nHidrata la soja y saltéala con cebolla y tomate triturado\nVacía las berenjenas y mezcla la pulpa con el relleno\nRellena, cubre con queso rallado y orégano\nGratina 10 minutos", "raciones": 2, "prep_min": 20, "cocina_min": 40, "tags": ["veggie", "horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "berenjena", "q": 2, "u": "pieza"}, {"n": "soja texturizada", "q": 60, "u": "g"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Espinacas con garbanzos a la sevillana", "descripcion": "Clásico andaluz de garbanzos y espinacas con majado de pan, ajo y comino.", "instrucciones": "Fríe el pan en dados con los ajos y machácalos con comino y vinagre\nSaltea las espinacas hasta que reduzcan\nAñade los garbanzos y el pimentón\nIncorpora el majado con un poco de agua\nCocina 8 minutos hasta que espese", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["veggie", "sin-horno", "rapida"], "temporada": "invierno", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "espinacas", "q": 400, "u": "g"}, {"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "ajo", "q": 3, "u": "pieza"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salteado de quinoa con champiñones y almendras", "descripcion": "Quinoa salteada con calabacín, pimiento y champiñones con toque de soja.", "instrucciones": "Cuece la quinoa 15 minutos y escurre\nSaltea ajo, calabacín, pimiento y champiñones\nAñade la quinoa y la salsa de soja\nSaltea 3 minutos más\nSirve con almendras tostadas picadas", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["veggie", "sin-horno", "fiambrera", "rapida"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "quinoa", "q": 150, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "champiñones", "q": 150, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "almendras", "q": 30, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Dal de lentejas con arroz", "descripcion": "Lentejas especiadas al estilo indio con leche de coco y arroz basmati.", "instrucciones": "Sofríe cebolla y ajo con curry y comino\nAñade las lentejas, el tomate triturado y agua\nCuece 25 minutos hasta que las lentejas se deshagan\nIncorpora la leche de coco y cocina 5 minutos\nSirve con arroz cocido", "raciones": 2, "prep_min": 10, "cocina_min": 40, "tags": ["veggie", "guiso", "sin-horno", "fiambrera"], "temporada": "invierno", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 180, "u": "g"}, {"n": "leche de coco", "q": 200, "u": "ml"}, {"n": "curry", "q": 2, "u": "cdta"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "tomate triturado", "q": 200, "u": "g"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Albóndigas de garbanzos al horno con yogur", "descripcion": "Albóndigas vegetales tipo falafel horneadas con salsa de yogur y limón.", "instrucciones": "Tritura los garbanzos con ajo, comino y sal\nMezcla con huevo y pan rallado y forma bolas\nHornéalas 25 minutos a 200 grados girando a mitad\nMezcla el yogur con limón y sal\nSirve las albóndigas con la salsa", "raciones": 2, "prep_min": 20, "cocina_min": 30, "tags": ["veggie", "horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "garbanzos cocidos", "q": 400, "u": "g"}, {"n": "pan rallado", "q": 60, "u": "g"}, {"n": "huevo", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "yogur griego", "q": 1, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tofu a la plancha con puré de boniato", "descripcion": "Filetes de tofu marinados en soja con puré cremoso de boniato y judías verdes.", "instrucciones": "Marina el tofu en salsa de soja y pimentón 10 minutos\nCuece el boniato y tritúralo con mantequilla y leche\nCuece las judías verdes al vapor\nMarca el tofu en plancha caliente 3 minutos por lado\nSirve con el puré y las judías", "raciones": 2, "prep_min": 20, "cocina_min": 25, "tags": ["veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "tofu", "ingredientes": [{"n": "tofu", "q": 300, "u": "g"}, {"n": "boniato", "q": 2, "u": "pieza"}, {"n": "judías verdes", "q": 200, "u": "g"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "mantequilla", "q": 15, "u": "g"}, {"n": "leche", "q": 50, "u": "ml"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Risotto cremoso de champiñones", "descripcion": "Arroz cremoso con champiñones, vino blanco, mantequilla y queso.", "instrucciones": "Sofríe la cebolla picada y los champiñones laminados\nAñade el arroz y rehoga 2 minutos\nMoja con el vino y deja evaporar\nVe añadiendo caldo caliente poco a poco durante 18 minutos\nTermina con mantequilla y queso rallado", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 180, "u": "g"}, {"n": "champiñones", "q": 250, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "caldo de verduras", "q": 700, "u": "ml"}, {"n": "mantequilla", "q": 20, "u": "g"}, {"n": "queso rallado", "q": 50, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Pasta con pesto de espinacas y nueces", "descripcion": "Pasta con pesto rápido de espinacas frescas, nueces y queso.", "instrucciones": "Cuece la pasta al dente reservando un poco de agua\nTritura espinacas, nueces, ajo, queso, aceite y zumo de limón\nMezcla el pesto con la pasta y un poco de agua de cocción\nSirve con queso rallado extra", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 200, "u": "g"}, {"n": "espinacas", "q": 100, "u": "g"}, {"n": "nueces", "q": 50, "u": "g"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Wok de verduras con cacahuetes y arroz", "descripcion": "Verduras crujientes al wok con arroz, soja y cacahuetes tostados.", "instrucciones": "Cuece el arroz y reserva\nSaltea ajo, zanahoria, brócoli, pimiento y champiñones a fuego fuerte\nAñade el arroz y la salsa de soja\nSaltea 2 minutos más\nSirve con cacahuetes por encima", "raciones": 2, "prep_min": 15, "cocina_min": 20, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "arroz", "q": 140, "u": "g"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "champiñones", "q": 150, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "cacahuetes", "q": 40, "u": "g"}, {"n": "salsa de soja", "q": 3, "u": "cda"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Estofado de alubias blancas con calabaza", "descripcion": "Alubias guisadas con calabaza, puerro y tomillo, reconfortante y ligero.", "instrucciones": "Sofríe el puerro y la zanahoria picados\nAñade la calabaza en dados y el pimentón\nIncorpora las alubias, el tomillo y el caldo\nGuisa 25 minutos a fuego suave\nAplasta unas alubias para espesar y sirve", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["veggie", "guiso", "sin-horno", "fiambrera"], "temporada": "otono", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "alubias blancas cocidas", "q": 400, "u": "g"}, {"n": "calabaza", "q": 300, "u": "g"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Tortilla de espinacas y queso feta", "descripcion": "Tortilla jugosa de espinacas salteadas con cebolla y queso feta.", "instrucciones": "Pocha la cebolla picada y añade las espinacas hasta que reduzcan\nBate los huevos y mezcla con las verduras y el feta desmigado\nCuaja la tortilla a fuego medio 4 minutos\nDale la vuelta y cocina 3 minutos más\nSirve con pan", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "huevo", "q": 5, "u": "pieza"}, {"n": "espinacas", "q": 200, "u": "g"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Cuscús especiado con verduras y garbanzos", "descripcion": "Cuscús al estilo magrebí con verduras salteadas, garbanzos y comino.", "instrucciones": "Saltea cebolla, zanahoria y calabacín en dados\nAñade los garbanzos, el comino y el curry\nHidrata el cuscús con el caldo caliente 5 minutos\nMezcla todo con un chorrito de aceite\nSirve templado o frío", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["veggie", "rapida", "sin-horno", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "cuscús", "q": 140, "u": "g"}, {"n": "garbanzos cocidos", "q": 200, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "comino", "q": 1, "u": "cdta"}, {"n": "curry", "q": 1, "u": "cdta"}, {"n": "caldo de verduras", "q": 200, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

-- ============================================================
-- Ensaladas y platos de temporada (15)
-- ============================================================

select seed_recipe($json$ {"nombre": "Gazpacho andaluz con picatostes", "descripcion": "Sopa fría de tomate, pepino y pimiento con pan frito crujiente.", "instrucciones": "Tritura tomate, pepino, pimiento, ajo y un pan remojado\nAñade aceite, vinagre y sal y tritura hasta que quede fino\nEnfría en nevera al menos 1 hora\nFríe el otro pan en dados para los picatostes\nSirve muy frío con los picatostes", "raciones": 2, "prep_min": 20, "cocina_min": 5, "tags": ["veggie", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "tomate", "q": 6, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "pan", "q": 2, "u": "pieza"}, {"n": "vinagre", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada griega con queso feta", "descripcion": "Tomate, pepino, cebolla y aceitunas con feta, orégano y buen aceite.", "instrucciones": "Corta el tomate y el pepino en trozos grandes\nCorta la cebolla en juliana fina\nAñade aceitunas y el feta en dados\nAliña con aceite, orégano y sal\nSirve con pan", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["ensalada", "veggie", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "tomate", "q": 2, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 150, "u": "g"}, {"n": "aceitunas", "q": 80, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "pan", "q": 1, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada campera con atún", "descripcion": "Ensalada fría de patata con huevo, atún, pimiento y aceitunas.", "instrucciones": "Cuece las patatas con piel 20 minutos y los huevos 10\nPela y corta las patatas y los huevos\nPica tomate, cebolla y pimiento verde\nMezcla con el atún y las aceitunas\nAliña con aceite, vinagre y sal y enfría", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["ensalada", "sin-horno", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "patata", "ingredientes": [{"n": "patata", "q": 3, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "atún en lata", "q": 80, "u": "g"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "aceitunas", "q": 50, "u": "g"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada de lentejas con feta", "descripcion": "Lentejas frías con pimiento, pepino, tomate y queso feta en vinagreta.", "instrucciones": "Cuece las lentejas 25 minutos, escurre y deja enfriar\nPica pimiento, tomate, cebolla y pepino muy finos\nMezcla con las lentejas y el feta desmigado\nAliña con aceite, vinagre y sal", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["ensalada", "veggie", "sin-horno", "fiambrera"], "temporada": "verano", "batch_days": 1, "principal": "legumbre", "ingredientes": [{"n": "lentejas", "q": 160, "u": "g"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "tomate", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "pepino", "q": 1, "u": "pieza"}, {"n": "queso feta", "q": 80, "u": "g"}, {"n": "vinagre", "q": 2, "u": "cda"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada césar de pollo", "descripcion": "Lechuga con pollo a la plancha, picatostes y salsa ligera de yogur y mostaza.", "instrucciones": "Marca la pechuga a la plancha y córtala en tiras\nTuesta el pan en dados con un poco de aceite\nMezcla yogur, mostaza, ajo majado y sal para la salsa\nMonta la ensalada con lechuga, pollo y picatostes\nTermina con la salsa y queso rallado", "raciones": 2, "prep_min": 15, "cocina_min": 15, "tags": ["ensalada", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "pechuga de pollo", "q": 300, "u": "g"}, {"n": "lechuga", "q": 1, "u": "pieza"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "yogur griego", "q": 1, "u": "pieza"}, {"n": "mostaza", "q": 1, "u": "cdta"}, {"n": "ajo", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Crema de calabaza y zanahoria", "descripcion": "Crema suave de calabaza asada y zanahoria con nata y nueces.", "instrucciones": "Sofríe la cebolla picada\nAñade calabaza, zanahoria y patata en trozos\nCubre con caldo y cuece 25 minutos\nTritura con la nata hasta que quede fina\nSirve con nueces picadas por encima", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "sin-horno"], "temporada": "otono", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabaza", "q": 600, "u": "g"}, {"n": "zanahoria", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "nata para cocinar", "q": 100, "u": "ml"}, {"n": "nueces", "q": 30, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Crema de calabacín con queso fresco", "descripcion": "Crema ligera de calabacín y puerro triturada con queso fresco.", "instrucciones": "Sofríe la cebolla y el calabacín troceado\nAñade la patata y el caldo y cuece 20 minutos\nTritura con el queso fresco\nRectifica de sal\nSirve con pan tostado", "raciones": 2, "prep_min": 10, "cocina_min": 25, "tags": ["veggie", "sin-horno", "rapida"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "calabacín", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "queso fresco", "q": 100, "u": "g"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Alcachofas salteadas con jamón", "descripcion": "Corazones de alcachofa dorados con ajo y jamón serrano.", "instrucciones": "Limpia las alcachofas y cuécelas 15 minutos en agua con limón\nEscurre y córtalas en cuartos\nDora el ajo laminado en aceite\nSaltea las alcachofas hasta que se doren\nAñade el jamón al final y sirve con pan", "raciones": 2, "prep_min": 20, "cocina_min": 25, "tags": ["sin-horno"], "temporada": "primavera", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "alcachofa", "q": 6, "u": "pieza"}, {"n": "jamón serrano", "q": 80, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Espárragos verdes con huevo y patata", "descripcion": "Espárragos a la plancha con huevos a baja temperatura y patata cocida.", "instrucciones": "Cuece las patatas en rodajas gruesas\nMarca los espárragos en plancha con aceite y sal\nEscalfa los huevos 4 minutos en agua con vinagre\nMonta el plato y rompe el huevo por encima\nTermina con pimienta negra", "raciones": 2, "prep_min": 10, "cocina_min": 20, "tags": ["veggie", "sin-horno", "rapida"], "temporada": "primavera", "batch_days": 1, "principal": "huevo", "ingredientes": [{"n": "espárragos verdes", "q": 400, "u": "g"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada de pasta con atún y maíz", "descripcion": "Pasta fría con atún, tomate, maíz y aceitunas para llevar.", "instrucciones": "Cuece la pasta, refresca con agua fría y escurre\nPica los tomates y mezcla con el maíz y las aceitunas\nAñade el atún escurrido\nAliña con aceite, vinagre y sal\nGuarda en frío hasta servir", "raciones": 2, "prep_min": 10, "cocina_min": 15, "tags": ["ensalada", "sin-horno", "fiambrera", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "atun", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "atún en lata", "q": 120, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "maíz dulce", "q": 100, "u": "g"}, {"n": "aceitunas", "q": 60, "u": "g"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada caprese con aceitunas", "descripcion": "Tomate y mozzarella con orégano, aceitunas y pan crujiente.", "instrucciones": "Corta el tomate y la mozzarella en rodajas\nAlterna en un plato y añade las aceitunas\nAliña con aceite, vinagre, orégano y sal\nSirve con pan tostado", "raciones": 2, "prep_min": 10, "cocina_min": 0, "tags": ["ensalada", "veggie", "sin-horno", "rapida"], "temporada": "verano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "tomate", "q": 3, "u": "pieza"}, {"n": "mozzarella", "q": 250, "u": "g"}, {"n": "aceitunas", "q": 40, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "vinagre", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "pan", "q": 2, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Vichyssoise de puerro", "descripcion": "Crema fría francesa de puerro y patata con nata, ideal para el calor.", "instrucciones": "Pocha el puerro y la cebolla en mantequilla sin que tomen color\nAñade la patata y el caldo y cuece 25 minutos\nTritura con la nata hasta que quede muy fina\nEnfría en nevera al menos 2 horas\nSirve con pan tostado", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["veggie", "sin-horno"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "puerro", "q": 3, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 500, "u": "ml"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "mantequilla", "q": 15, "u": "g"}, {"n": "pan", "q": 1, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Crema de coliflor con queso", "descripcion": "Crema invernal de coliflor y puerro con leche y queso rallado.", "instrucciones": "Sofríe el puerro picado\nAñade la coliflor en ramilletes y la patata\nCubre con caldo y cuece 20 minutos\nTritura con la leche y el queso\nSirve caliente con pan tostado", "raciones": 2, "prep_min": 15, "cocina_min": 25, "tags": ["veggie", "sin-horno"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "coliflor", "q": 1, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "puerro", "q": 1, "u": "pieza"}, {"n": "caldo de verduras", "q": 600, "u": "ml"}, {"n": "leche", "q": 100, "u": "ml"}, {"n": "queso rallado", "q": 40, "u": "g"}, {"n": "pan", "q": 1, "u": "pieza"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Ensalada de espinacas, fresas y feta", "descripcion": "Ensalada primaveral de espinacas frescas con fresas, nueces y queso feta.", "instrucciones": "Lava las espinacas y las fresas\nCorta las fresas en láminas\nMezcla con el feta desmigado y las nueces\nAliña con aceite, vinagre y miel\nSirve con pan", "raciones": 2, "prep_min": 15, "cocina_min": 0, "tags": ["ensalada", "veggie", "sin-horno", "rapida"], "temporada": "primavera", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "espinacas", "q": 150, "u": "g"}, {"n": "fresas", "q": 200, "u": "g"}, {"n": "queso feta", "q": 100, "u": "g"}, {"n": "nueces", "q": 40, "u": "g"}, {"n": "vinagre", "q": 2, "u": "cda"}, {"n": "miel", "q": 1, "u": "cda"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}, {"n": "pan", "q": 1, "u": "pieza"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Pisto manchego con huevo", "descripcion": "Pisto de verduras de verano con tomate y huevos cuajados encima.", "instrucciones": "Sofríe la cebolla y los pimientos picados 10 minutos\nAñade berenjena y calabacín en dados y cocina 10 minutos\nIncorpora el tomate triturado y guisa 15 minutos\nCasca los huevos encima y tapa hasta que cuajen\nSirve caliente", "raciones": 2, "prep_min": 20, "cocina_min": 40, "tags": ["veggie", "sin-horno", "guiso"], "temporada": "verano", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "calabacín", "q": 1, "u": "pieza"}, {"n": "berenjena", "q": 1, "u": "pieza"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "pimiento verde", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

-- ============================================================
-- Elaboradas de fin de semana con horno (20)
-- ============================================================

select seed_recipe($json$ {"nombre": "Pollo asado al limón con patatas", "descripcion": "Muslos de pollo asados con patatas, cebolla, limón y tomillo.", "instrucciones": "Salpimienta los muslos y mézclalos con tomillo y aceite\nCorta patatas y cebolla en gajos y ponlos de cama en la fuente\nColoca el pollo encima con el limón en rodajas\nRiega con vino blanco\nHornea 60 minutos a 190 grados girando a mitad", "raciones": 4, "prep_min": 15, "cocina_min": 60, "tags": ["horno", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 1000, "u": "g"}, {"n": "patata", "q": 4, "u": "pieza"}, {"n": "cebolla", "q": 2, "u": "pieza"}, {"n": "limón", "q": 1, "u": "pieza"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Lasaña de carne y verduras", "descripcion": "Lasaña clásica con boloñesa casera, bechamel y queso gratinado.", "instrucciones": "Sofríe cebolla, zanahoria y la carne picada\nAñade el tomate triturado y cocina 20 minutos\nPrepara la bechamel con mantequilla, harina y leche\nMonta capas de pasta, boloñesa y bechamel\nCubre con queso y hornea 40 minutos a 180 grados", "raciones": 4, "prep_min": 40, "cocina_min": 40, "tags": ["horno", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "pasta", "q": 200, "u": "g"}, {"n": "carne picada mixta", "q": 500, "u": "g"}, {"n": "tomate triturado", "q": 400, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "zanahoria", "q": 1, "u": "pieza"}, {"n": "leche", "q": 500, "u": "ml"}, {"n": "harina de trigo", "q": 40, "u": "g"}, {"n": "mantequilla", "q": 40, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Lomo de cerdo asado con manzana", "descripcion": "Lomo de cerdo al horno con manzanas, cebolla y glaseado de miel y mostaza.", "instrucciones": "Unta el lomo con mostaza, miel, sal y aceite\nColoca en fuente con cebolla, patata y manzana en gajos\nRiega con el vino blanco\nHornea 50 minutos a 180 grados regando de vez en cuando\nDeja reposar 10 minutos antes de filetear", "raciones": 4, "prep_min": 15, "cocina_min": 55, "tags": ["horno", "batch"], "temporada": "otono", "batch_days": 2, "principal": "cerdo", "ingredientes": [{"n": "lomo de cerdo", "q": 700, "u": "g"}, {"n": "manzana", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 2, "u": "pieza"}, {"n": "patata", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 150, "u": "ml"}, {"n": "miel", "q": 1, "u": "cda"}, {"n": "mostaza", "q": 2, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Berenjenas rellenas de carne gratinadas", "descripcion": "Berenjenas asadas rellenas de carne picada con tomate y queso fundido.", "instrucciones": "Asa las berenjenas partidas por la mitad 25 minutos\nSofríe la cebolla y la carne picada\nAñade el tomate frito y la pulpa de la berenjena\nRellena las berenjenas y cubre con queso y orégano\nGratina 12 minutos", "raciones": 2, "prep_min": 20, "cocina_min": 40, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "berenjena", "q": 2, "u": "pieza"}, {"n": "carne picada de ternera", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 150, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Macarrones gratinados con chorizo", "descripcion": "Macarrones con tomate y chorizo gratinados con queso al horno.", "instrucciones": "Cuece la pasta al dente\nSofríe la cebolla y el chorizo en rodajas\nMezcla con el tomate frito y la pasta\nPasa a una fuente y cubre con queso y orégano\nGratina 15 minutos a 200 grados", "raciones": 2, "prep_min": 15, "cocina_min": 30, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pasta", "ingredientes": [{"n": "pasta", "q": 220, "u": "g"}, {"n": "chorizo", "q": 100, "u": "g"}, {"n": "tomate frito", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bacalao al horno con pimientos", "descripcion": "Lomos de bacalao horneados sobre patata panadera con pimientos y cebolla.", "instrucciones": "Hornea las patatas en rodajas con cebolla, pimiento y aceite 25 minutos\nColoca el bacalao encima con ajo laminado\nRiega con vino blanco\nHornea 15 minutos más a 190 grados", "raciones": 2, "prep_min": 15, "cocina_min": 40, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pescado", "ingredientes": [{"n": "bacalao", "q": 400, "u": "g"}, {"n": "pimiento rojo", "q": 2, "u": "pieza"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "vino blanco", "q": 100, "u": "ml"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Pimientos rellenos de arroz y carne", "descripcion": "Pimientos rojos asados rellenos de arroz con carne y tomate, gratinados.", "instrucciones": "Cuece el arroz y reserva\nSofríe cebolla y carne picada y mezcla con tomate frito y arroz\nCorta la tapa de los pimientos y rellénalos\nHornea 35 minutos a 180 grados tapados con su tapa\nCubre con queso y gratina 10 minutos", "raciones": 2, "prep_min": 25, "cocina_min": 45, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "ternera", "ingredientes": [{"n": "pimiento rojo", "q": 4, "u": "pieza"}, {"n": "arroz", "q": 120, "u": "g"}, {"n": "carne picada de ternera", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 150, "u": "g"}, {"n": "queso rallado", "q": 60, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Coliflor gratinada con bechamel y jamón", "descripcion": "Coliflor cocida con bechamel casera, jamón cocido y queso gratinado.", "instrucciones": "Cuece la coliflor en ramilletes 10 minutos y escurre\nPrepara la bechamel con mantequilla, harina y leche\nMezcla la coliflor con el jamón en tiras en una fuente\nCubre con la bechamel y el queso\nGratina 20 minutos a 200 grados", "raciones": 2, "prep_min": 20, "cocina_min": 30, "tags": ["horno"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "coliflor", "q": 1, "u": "pieza"}, {"n": "leche", "q": 500, "u": "ml"}, {"n": "harina de trigo", "q": 40, "u": "g"}, {"n": "mantequilla", "q": 40, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "jamón cocido", "q": 100, "u": "g"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Pastel de patata y carne al horno", "descripcion": "Pastel tipo parmentier de carne guisada cubierta de puré gratinado.", "instrucciones": "Cuece las patatas y haz un puré con leche y mantequilla\nSofríe cebolla y carne picada y añade el tomate frito\nExtiende la carne en una fuente y cubre con el puré\nEspolvorea queso rallado\nGratina 25 minutos a 200 grados", "raciones": 4, "prep_min": 30, "cocina_min": 45, "tags": ["horno", "batch"], "temporada": "invierno", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "patata", "q": 5, "u": "pieza"}, {"n": "carne picada mixta", "q": 500, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 100, "u": "g"}, {"n": "leche", "q": 100, "u": "ml"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Muslos de pollo a la miel y mostaza", "descripcion": "Muslos de pollo glaseados con miel, mostaza y soja con boniato asado.", "instrucciones": "Mezcla miel, mostaza, salsa de soja y aceite\nEmbadurna los muslos con la mezcla\nCorta el boniato en gajos y colócalo en la fuente\nHornea 45 minutos a 190 grados regando a mitad\nTermina con sésamo por encima", "raciones": 2, "prep_min": 10, "cocina_min": 45, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "pollo", "ingredientes": [{"n": "muslo de pollo", "q": 600, "u": "g"}, {"n": "boniato", "q": 2, "u": "pieza"}, {"n": "miel", "q": 2, "u": "cda"}, {"n": "mostaza", "q": 2, "u": "cdta"}, {"n": "salsa de soja", "q": 2, "u": "cda"}, {"n": "sésamo", "q": 10, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Salchichas al horno con patatas y pimientos", "descripcion": "Bandeja de salchichas frescas asadas con patata, pimiento y cebolla.", "instrucciones": "Corta patatas, pimientos y cebolla en trozos grandes\nMezcla con aceite, pimentón, tomillo y sal\nHornea las verduras 20 minutos a 200 grados\nAñade las salchichas y hornea 25 minutos más\nRemueve a mitad de cocción", "raciones": 2, "prep_min": 15, "cocina_min": 45, "tags": ["horno"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "cerdo", "ingredientes": [{"n": "salchichas frescas", "q": 400, "u": "g"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "pimiento verde", "q": 2, "u": "pieza"}, {"n": "cebolla", "q": 2, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "tomillo", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Empanada gallega de atún", "descripcion": "Empanada casera de masa fina rellena de sofrito de atún, pimiento y tomate.", "instrucciones": "Amasa harina, levadura, aceite, sal y agua templada y deja reposar 30 minutos\nSofríe cebolla y pimiento y mezcla con tomate frito y atún\nEstira la mitad de la masa y cubre con el relleno frío\nTapa con la otra mitad, sella y pinta con huevo\nHornea 40 minutos a 180 grados", "raciones": 4, "prep_min": 40, "cocina_min": 40, "tags": ["horno", "batch", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "atun", "ingredientes": [{"n": "harina de trigo", "q": 400, "u": "g"}, {"n": "levadura", "q": 10, "u": "g"}, {"n": "atún en lata", "q": 240, "u": "g"}, {"n": "tomate frito", "q": 200, "u": "g"}, {"n": "pimiento rojo", "q": 1, "u": "pieza"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "huevo", "q": 2, "u": "pieza"}, {"n": "aceite de oliva", "q": 4, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Quiche de puerro y bacon", "descripcion": "Tarta salada de masa quebrada con puerro pochado, bacon y crema de huevo.", "instrucciones": "Mezcla harina, mantequilla fría y sal y forma la masa\nForra un molde y hornea en blanco 12 minutos\nPocha el puerro y dora el bacon\nBate huevos con nata y mezcla con el relleno y el queso\nVierte en el molde y hornea 30 minutos a 180 grados", "raciones": 4, "prep_min": 30, "cocina_min": 45, "tags": ["horno", "batch", "fiambrera"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "huevo", "ingredientes": [{"n": "harina de trigo", "q": 200, "u": "g"}, {"n": "mantequilla", "q": 100, "u": "g"}, {"n": "huevo", "q": 4, "u": "pieza"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "puerro", "q": 2, "u": "pieza"}, {"n": "bacon", "q": 100, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "sal", "q": 1, "u": "cdta"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Pizza casera de champiñones y mozzarella", "descripcion": "Pizza de masa casera con tomate, mozzarella, champiñones y aceitunas.", "instrucciones": "Amasa harina, levadura, agua, sal y aceite y deja levar 1 hora\nEstira la masa en una bandeja\nCubre con tomate frito, mozzarella, champiñones laminados y aceitunas\nHornea 15 minutos a 250 grados\nTermina con orégano", "raciones": 2, "prep_min": 30, "cocina_min": 20, "tags": ["horno", "veggie"], "temporada": "todo-el-ano", "batch_days": 1, "principal": "queso", "ingredientes": [{"n": "harina de trigo", "q": 300, "u": "g"}, {"n": "levadura", "q": 7, "u": "g"}, {"n": "tomate frito", "q": 150, "u": "g"}, {"n": "mozzarella", "q": 200, "u": "g"}, {"n": "champiñones", "q": 150, "u": "g"}, {"n": "aceitunas", "q": 40, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Musaka de berenjena y ternera", "descripcion": "Capas de berenjena asada y carne especiada con canela bajo bechamel gratinada.", "instrucciones": "Asa las berenjenas en láminas con aceite 20 minutos\nSofríe cebolla y carne y añade tomate triturado y canela\nPrepara la bechamel con mantequilla, harina y leche\nMonta capas de berenjena y carne y cubre con bechamel y queso\nHornea 40 minutos a 180 grados", "raciones": 4, "prep_min": 35, "cocina_min": 60, "tags": ["horno", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "berenjena", "q": 3, "u": "pieza"}, {"n": "carne picada de ternera", "q": 400, "u": "g"}, {"n": "tomate triturado", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "canela", "q": 1, "u": "cdta"}, {"n": "leche", "q": 400, "u": "ml"}, {"n": "harina de trigo", "q": 30, "u": "g"}, {"n": "mantequilla", "q": 30, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "aceite de oliva", "q": 3, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Calabacines rellenos de pavo gratinados", "descripcion": "Barquitas de calabacín rellenas de pavo picado con tomate y queso.", "instrucciones": "Parte los calabacines a lo largo y vacíalos\nHornea las barquitas 15 minutos a 190 grados\nSaltea la cebolla, el pavo picado y la pulpa del calabacín\nAñade el tomate frito y el orégano\nRellena, cubre con queso y gratina 15 minutos", "raciones": 2, "prep_min": 20, "cocina_min": 35, "tags": ["horno"], "temporada": "verano", "batch_days": 1, "principal": "pavo", "ingredientes": [{"n": "calabacín", "q": 3, "u": "pieza"}, {"n": "filete de pavo", "q": 300, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "tomate frito", "q": 100, "u": "g"}, {"n": "queso rallado", "q": 80, "u": "g"}, {"n": "orégano", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Canelones de carne y espinacas", "descripcion": "Canelones rellenos de carne y espinacas con bechamel y queso gratinado.", "instrucciones": "Cuece las placas de pasta y extiéndelas sobre un paño\nSofríe cebolla, carne y espinacas hasta que seque\nRellena y enrolla los canelones\nPrepara la bechamel y cubre los canelones con ella y el queso\nHornea 25 minutos a 190 grados", "raciones": 4, "prep_min": 45, "cocina_min": 35, "tags": ["horno", "batch"], "temporada": "invierno", "batch_days": 2, "principal": "ternera", "ingredientes": [{"n": "pasta", "q": 180, "u": "g"}, {"n": "carne picada mixta", "q": 400, "u": "g"}, {"n": "espinacas", "q": 150, "u": "g"}, {"n": "cebolla", "q": 1, "u": "pieza"}, {"n": "leche", "q": 500, "u": "ml"}, {"n": "harina de trigo", "q": 40, "u": "g"}, {"n": "mantequilla", "q": 40, "u": "g"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Gratinado de brócoli y patata", "descripcion": "Brócoli y patata al horno con nata, ajo y queso fundido por encima.", "instrucciones": "Cuece la patata en rodajas 10 minutos y el brócoli 5\nFrota una fuente con ajo y coloca las verduras en capas\nSalpimienta y vierte la nata\nCubre con el queso rallado\nHornea 30 minutos a 190 grados", "raciones": 2, "prep_min": 15, "cocina_min": 35, "tags": ["horno", "veggie"], "temporada": "invierno", "batch_days": 1, "principal": "verdura", "ingredientes": [{"n": "brócoli", "q": 1, "u": "pieza"}, {"n": "patata", "q": 3, "u": "pieza"}, {"n": "nata para cocinar", "q": 200, "u": "ml"}, {"n": "queso rallado", "q": 100, "u": "g"}, {"n": "ajo", "q": 2, "u": "pieza"}, {"n": "pimienta negra", "q": 1, "u": "cdta"}, {"n": "aceite de oliva", "q": 1, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Arroz al horno con garbanzos y chorizo", "descripcion": "Arroz valenciano al horno con garbanzos, chorizo, patata y cabeza de ajos.", "instrucciones": "Dora el chorizo y la patata en rodajas en una cazuela apta para horno\nAñade el tomate rallado y el pimentón\nIncorpora el arroz, los garbanzos y el caldo caliente\nColoca la cabeza de ajos en el centro\nHornea 35 minutos a 200 grados sin remover", "raciones": 2, "prep_min": 15, "cocina_min": 40, "tags": ["horno"], "temporada": "invierno", "batch_days": 1, "principal": "arroz", "ingredientes": [{"n": "arroz", "q": 200, "u": "g"}, {"n": "garbanzos cocidos", "q": 200, "u": "g"}, {"n": "chorizo", "q": 100, "u": "g"}, {"n": "tomate", "q": 2, "u": "pieza"}, {"n": "patata", "q": 1, "u": "pieza"}, {"n": "ajo", "q": 4, "u": "pieza"}, {"n": "pimentón", "q": 1, "u": "cdta"}, {"n": "caldo de pollo", "q": 500, "u": "ml"}, {"n": "aceite de oliva", "q": 2, "u": "cda"}]} $json$::jsonb);

select seed_recipe($json$ {"nombre": "Bizcocho de chocolate y nueces", "descripcion": "Bizcocho casero esponjoso de chocolate negro fundido con nueces.", "instrucciones": "Funde el chocolate con la mantequilla al baño maría\nBate los huevos con el azúcar hasta blanquear\nMezcla con el chocolate, la leche, la harina y la levadura\nAñade las nueces troceadas\nHornea 40 minutos a 175 grados y deja enfriar", "raciones": 4, "prep_min": 20, "cocina_min": 45, "tags": ["horno", "dulce", "veggie", "batch"], "temporada": "todo-el-ano", "batch_days": 2, "principal": "huevo", "ingredientes": [{"n": "chocolate negro", "q": 100, "u": "g"}, {"n": "mantequilla", "q": 80, "u": "g"}, {"n": "huevo", "q": 3, "u": "pieza"}, {"n": "azúcar", "q": 100, "u": "g"}, {"n": "harina de trigo", "q": 150, "u": "g"}, {"n": "levadura", "q": 10, "u": "g"}, {"n": "leche", "q": 50, "u": "ml"}, {"n": "nueces", "q": 40, "u": "g"}]} $json$::jsonb);

select validate_seed_recipes();
